\documentclass[pdflatex, sn-nature]{sn-jnl}

\usepackage{xr}
\usepackage{manyfoot}
\usepackage{amsmath}
\externaldocument[SM-]{../supplementary/sup_mat}
\externaldocument[ED-]{../extended_data/ext_data}

\usepackage{lineno}

\newcommand{\todo}[1]{\textcolor{red}{\textbf{(#1)}}}
\newcommand{\degr}{$^{\circ{}}$C}
\newcommand{\degg}{$^{\circ{}}$}

% Light formatting for figure caption list in back matter.
\makeatletter

% No title
\renewcommand{\listoffigures}{%
  \ifhmode\unskip\par\fi
  \begingroup
    \let\hyper@linkstart\@gobbletwo % disable links
    \let\hyper@linkend\relax
    \@starttoc{lof}
  \endgroup
}

% Custom entries: spacing, no dots, no page numbers, space after number
\renewcommand*\l@figure[2]{%
  \addvspace{\baselineskip}%
  \noindent
  \begingroup
    \renewcommand\numberline[1]{Figure~##1\hspace{1em}}%
    #1\par
  \endgroup
}

\makeatother

\begin{document}
\linenumbers

%TC:ignore
\title{Shifting hail hazard under global warming and effects on crop hail risk}

\author*[1,2,3,4]{\fnm{Timothy H.} \sur{Raupach}}\email{timothy.h.raupach@gmail.com}
\author[5,6]{\fnm{Raphael} \sur{Portmann}}
\author[7]{\fnm{Christian} \sur{Siderius}}
\author[2,3,4]{\fnm{Steven C.} \sur{Sherwood}}

\affil[1]{\orgdiv{Institute for Climate Risk and Response}, \orgname{UNSW Sydney}, \orgaddress{\street{Mathews Building Level 4}, \city{The University of New South Wales, Sydney}, \postcode{2051}, \state{NSW}, \country{Australia}}}
\affil[2]{\orgdiv{Climate Change Research Centre}, \orgname{UNSW Sydney}, \orgaddress{\country{Australia}}}
\affil[3]{\orgdiv{ARC Centre of Excellence for Climate Extremes}, \orgname{UNSW Sydney}, \orgaddress{\country{Australia}}}
\affil[4]{\orgdiv{ARC Centre of Excellence for 21st Century Weather}, \orgname{UNSW Sydney}, \orgaddress{\country{Australia}}}
\affil[5]{\orgdiv{Agroscope}, \orgname{Climate and Agriculture}, \orgaddress{\city{Zurich}, \country{Switzerland (prev. address)}}}
\affil[6]{\orgname{Planval}, \orgaddress{\city{Bern}, \country{Switzerland}}}
\affil[7]{\orgname{Uncharted Waters}, \orgaddress{\city{Sydney}, \country{Australia}}}

\abstract{Hailstorms cause damage across the globe and endanger crops, but their
changes in a warming climate are not well quantified. Here we apply three hail
proxies to an ensemble of global model projections to show divergent changes in
hail-prone condition frequency worldwide. Changes depend on whether the proxy
allows instability increases to be offset by temperature or moisture increases.
Uncertainty on hail projections remains high, especially in the tropics. In
projections with 2\degr{} and 3\degr{} of mean global warming, ensemble-mean
hail-prone conditions shifted poleward, with decreases in hail hazard in the
mid-latitudes and increases in colder regions. Across 26 crop types with fixed
exposure and vulnerability, hail risk was generally projected to increase for
winter crops such as wheat and decrease for summer crops such as maize. Poleward
shifts in hail hazard may attenuate yield increases from similar shifts in crop
regions under climate change.}

%% NCC:
%% Abstract: 150 words
%% Main text – up to 3,000 words, excluding abstract, online Methods, references and figure legends.
%% Up to 6 display items.
%% Up to 50 references.
%% No subheadings in discussion.

\keywords{hail, severe weather, convection, trends, projections}

\maketitle

<<loadResults, echo=FALSE, results=FALSE>>=
#library(rjson)
#library(data.table)
#results = fromJSON(file='../../results/results.json')
@
%TC:endignore

Hailstorms are a form of extreme weather that causes substantial damage to
physical assets including crops. Hail and the storms that produce it are
expected to be affected by anthropogenic global warming, yet regional studies
using observations or projections show geographical inhomogeneities and there
remains high uncertainty on the details of changes \cite{Raupach_NREE_2021}.
Globally, hail observations are scarce \cite{Raupach_NREE_2021}, meaning global
climatologies generally rely on satellite data \cite{Bang_JAMC_2019} or
examination of environmental conditions in reanalyses using hail proxies
\cite{Prein_WCE_2018}. We produced global projections of future hail hazard
using hail proxies applied to model output from the Coupled Model
Intercomparison Project (CMIP6) \cite{Eyring_GMD_2016} in a per-degree
framework, and used them to analyse projected changes in hail frequency and
resulting changes in hail risk to crops.

Because hailstorms are hard to observe and model owing to their small spatial
size and relative rarity \cite{Raupach_NREE_2021}, climatological studies often
use proxies that detect hail-prone conditions. Hail proxies rely on detecting
the atmospheric ``ingredients'' required for hail to form. Hailstones form by
accretion of supercooled liquid water onto ice embryos suspended in the updraft
of a thunderstorm, until they become too heavy to support, after which they fall
while melting on their descent through warmer air \cite{Knight_2001}. Hailstorm
ingredients are usually considered to include, at minimum, atmospheric
instability to allow for a thunderstorm with strong updrafts that can support
hail growth to form \cite{Brooks_AR_2003}, and vertical wind shear (differences
in horizontal wind by height) to ``organise'' the storm \cite{Brooks_AR_2013}
and influence hailstone trajectories \cite{Lin_JAS_2022, Fischer_JAS_2025}.
Instability--shear hail proxies are common, but may overestimate hail in
tropical regions where instability is often high and wind shear may better
discriminate hailstorm environments \cite{Raupach_MWR_2023}. Proxies also suffer
from the ``initiation problem'', in that storms rarely initiate even in
storm-prone conditions \cite{Tippett_CCCR_2015}.

Climate change is expected to affect the ingredients for hailstorms and thus the
frequency and severity of hail \cite{Raupach_NREE_2021}. A thermodynamic
expectation is of three offsetting effects: first, increased instability owing
to a larger saturation deficit in a warmer atmosphere \cite{Seeley_GRL_2015}
leading to more storm initiation and stronger updrafts that could support larger
hailstones; second, increased melting of hailstones owing to a warmer
troposphere \cite{Prein_NCC_2020}, leading to a reduction (or elimination
\cite{Mahoney_NCC_2012}) of surface hail frequency; and third, an overall
decrease in vertical wind shear \cite{Brooks_AR_2013} that is often outweighed
by changes in instability \cite{Trapp_GRL_2009} and may not apply locally
\cite{Radler_npjCAS_2019}. The broad thermodynamic expectation is of reduced
surface hail frequency combined with increased severity when hail does reach the
Earth's surface \cite{Raupach_NREE_2021}. However, regional studies show large
geographical heterogeneity in hail frequency trends, owing partly to offsetting
effects and partly to changes in large-scale dynamics meaning that ingredient
changes are not spatially uniform, while hail severity is generally expected to
increase \cite{Raupach_NREE_2021}. Process uncertainties, such as those around
the influence of changes in aerosol concentrations, also remain
\cite{Raupach_NREE_2021}.

Hailstorms can damage crops by wounding plants and increasing pathogen infection
\cite{Battaglia_CS_2019}, breaking stems, defoliating, or crushing plants
\cite{Dhillon_CJPS_2021}, resulting in substantial yield losses
\cite{Dhillon_CJPS_2021}. Factors that affect crop damage inflicted by hail
include the hailstone size \cite{Changnon_JAMC_1971} and number of hailstones
per area \cite{Yue_PLOSONE_2019}, coincident horizontal wind
\cite{Morgan_JAMC_1976}, and crop growth stage \cite{Sanchez_JAMC_1996,
Dhillon_CJPS_2021,Yue_PLOSONE_2019}. Correlations between temperature and
hailstorm damage in Europe \cite{Dessens_GRL_1995} have been used to project
regional increases in damage with warming \cite{Botzen_REE_2010}, and in
Switzerland, an increase in hail days has increased hail risk to winter wheat
despite the harvesting date becoming earlier as temperatures increase
\cite{Portmann_MZ_2025}. However, no global picture on possible climate-induced
changes to hail risk for crops has emerged.

Here, we applied three globally realistic hail proxies -- the Raupach, Eccel,
and SHIP proxies -- to an ensemble of eight global projections from CMIP6, to
examine projections of the frequency of hail-prone conditions globally. We used
a per-degree framework \cite{Lepore_EF_2021} for simpler comparisons between
models. For details of the simulations and proxies used, refer to ``Online
methods'' and the supplementary information. To validate the global proxy
climatology, we compared the multimodel, multi-proxy ensemble climatology to
published local climatologies. We examined relative changes in hail-prone
conditions between historical and warmer periods, overall and seasonally, and
identified the primary drivers of changes. As a sensitivity study, we
investigated the effects of projected changes on hail-prone proportions of
time-invariant crop growing seasons for 26 different crops. Generally, hailstorm
frequency is projected to shift poleward, with decreases in warmer environments
and increases in cooler environments in future, driven primarily by increases in
convective instability and offset by temperature or moisture increases. Our
sensitivity analysis shows that generally the projected changes would increase
hail occurrence risk to winter crops, while decreasing occurrence risk for
summer crops.

\subsection*{Climatology and proxy validation}

The multimodel, multi-proxy climatology of normalised annual hail-prone days for
1980--1999 highlights known hail-prone regions globally (Figure
\ref{fig:cmip_era_climatology}). While individual CMIP6 models produced a wide
range of absolute values of hail-prone days, the locations of hail hotspots
agreed well between reanalysis and models (Extended Data Figure
\ref{ED-fig:historical_annual_means}). Different proxies highlighted similar
geographical regions but differed in magnitudes of hail-prone days, with the
Significant Hail Parameter (SHIP) \cite{SPC_SHIP} producing the fewest, and the
Eccel proxy \cite{Eccel_IJC_2012} producing the greatest number of hail-prone
days. Given the broad geographical agreement but differences in absolute numbers
of hail-prone days, we use annual hail-prone days normalised by per-proxy
per-model maxima, and focus primarily on changes in multi-proxy, multimodel mean
annual normalised hail-prone days in our analyses. 

The Raupach, Eccel, and SHIP proxies were trained in Australia
\citep{Raupach_MWR_2023}, Italy \citep{Eccel_IJC_2012}, and the USA
\citep{SPC_SHIP}, respectively, so to validate their use globally we performed a
detailed comparison between the ensemble proxy results and published
climatologies worldwide (Supplementary Section \ref{SM-sec:proxy_validation} and
Supplementary Figures
\ref{SM-fig:proxy_climatology_asia}--\ref{SM-fig:proxy_climatology_africa}). The
Raupach proxy was designed to adapt to latitudinal changes in hail environments
and was trained in Australia using data from the tropics to mid-latitudes,
covering most environments in which hail is expected \citep{Raupach_MWR_2023}.
Generally, spatial agreement of the proxy ensemble with published climatologies
was strong. The proxy ensemble disagreed with station reports (but not satellite
or proxy studies) over the Tibetan Plateau, and in the USA some ensemble members
placed the peak hail risk on the Gulf Coast rather than on the Great Plains. The
proxy ensemble showed greater inter-model-proxy disagreement over the tropics
than the mid-latitudes. Multi-proxy means were able to identify particularly
hail-prone conditions in case studies in areas in which the proxies were not
trained (Supplementary Section \ref{SM-sec:cases} and Supplementary Figures
\ref{SM-fig:anoms_India_2015}, \ref{SM-fig:anoms_Europe_2022}).

\begin{figure*}[!ht]
    \includegraphics[width=\textwidth]{../../results/main/CMIP6_ERA5_historical}
    \caption{\textbf{Hail proxies show known hail-prone regions that broadly
    agree with published climatologies}. Multimodel, multi-proxy mean (20 years,
    3 proxies, 8 models, n=480 samples per grid point) of normalised annual
    hail-prone days for CMIP6 models and ERA5 reanalysis for three selected
    proxies over the historical period (1980-1999) at 1$\times$1$^{\circ}$
    resolution.}
    \label{fig:cmip_era_climatology}
\end{figure*}

\subsection*{Changes in hail-prone days with warming}

Changes in multimodel, multi-proxy mean normalised annual hail-prone days for 2
\degr{} and 3 \degr{} of global warming show an overall poleward shift in
hail-prone conditions under both warming scenarios (Figure
\ref{fig:future_changes_hail_days}). Changes for 3 \degr{} warming were similar
to, but stronger than, those for 2 \degr{}. Changes generally agreed in sign
across the Raupach proxy and SHIP, while the pure instability--shear proxy of
Eccel \cite{Eccel_IJC_2012} produced contrasting increases leading to proxy
disagreement in the tropics (Extended Data Figure \ref{ED-fig:hail_diffs_3C}).
There were increases in hail-prone condition frequency projected across land
areas in central-north Asia, New Zealand, the southeast of Australia, North
America north of about 50\degg{} N and in the northwest USA, South America in
the southern Pampas and west to the Andes, and Europe north of about 60\degg{}
N, in the vicinity of the Alps, and southeast of the Black Sea (Figure
\ref{fig:future_changes_regional}). Decreases in hail-prone day frequency were
projected in southeast coastal areas of India and China (connecting in a band
across mainland Southeast Asia), northern Australia, the southeast USA and
Mexico, southeast South America east of the Andes between about 15\degg{} S and
30\degg{} S, and most of Africa south of 15\degg{} N (Figure
\ref{fig:future_changes_regional}). Some mid-latitude overall decreases in
hail-prone conditions were made up of warm-season decreases with smaller
increases in the cool season, for example in the southeast USA (Figure
\ref{fig:hail_changes_by_season}).

\begin{figure*}[!h]
    \includegraphics[width=\textwidth]{../../results/main/change_annual_hail_days_abs}
    \caption{\textbf{Hail-prone conditions shift under warming projections.}
    Changes in multi-proxy, multimodel mean annual hail-prone days (n=480 per
    grid point) for 2 \degr{} (a) and 3 \degr{} (b) of global warming. Stippling
    shows regions in which at least 50\% of the model/proxy combinations agreed
    with the sign of the mean difference and also showed significant differences
    in the mean ($p < 0.05$ using a two-sided Welch's t-test, n=20 years per
    epoch).}
    \label{fig:future_changes_hail_days}
\end{figure*}

\begin{figure*}[!h]
    \includegraphics[width=\textwidth]{../../results/main/regional_change}
    \caption{\textbf{Relative changes in multi-proxy, multimodel mean annual
    hail-prone days by region.} Changes are shown as a percentage of
    multi-proxy, multimodel mean normalised historical hail-prone days (n=480
    per grid point) over land, for 3\degr{} warming, for Asia (a), Oceania (b),
    North America (c), South America (d), Europe (e), and Africa (f). Region
    ``shorthand'' definitions are shown in Supplementary Section
    \ref{SM-sec:regions}. Stippling as for Figure
    \ref{fig:future_changes_hail_days}. Colour bars are shared across rows, and
    to increase contrast the colour bar for (a) is truncated.}
    \label{fig:future_changes_regional}
\end{figure*}

\begin{figure*}[!h]
    \centering
    \includegraphics[width=\textwidth]{../../results/main/hail_changes_by_season}
    \caption{\textbf{Changes in multimodel, multi-proxy mean seasonal hail-prone days for 3 \degr{} global warming.} n=480 per grid point. Seasons are December, January, February (DJF, a); March, April, May (MAM, b); June, July, August (JJA, c); and September, October, November (SON, d). Stippling as for Figure
    \ref{fig:future_changes_hail_days}.}
    \label{fig:hail_changes_by_season}
\end{figure*}

\subsection*{Drivers of the projected changes}

Projections showed increased extreme convective available potential energy
(CAPE), wide decreases in extreme wind shear, and increases in mean temperature
at 500 hPa and moist-unstable-parcel mixing ratio (Supplementary Section
\ref{SM-sec:projected_ingredients} and Supplementary Figures
\ref{SM-fig:ingredients_changes_1}--\ref{SM-fig:ingredients_changes_at_extreme_times}).
The main drivers of projected changes in this study, measured as the difference
between projected changes and changes when the future values for single
ingredients were de-biased, depended on the proxy (Figure \ref{fig:drivers}).
Overall, increases in hail-prone environment frequency were driven by
instability increases, while reductions in hail-prone environment frequency were
driven by temperature-related or moisture-related (for SHIP) ingredients. The
sums of changes across de-biased ingredients were close to the projected changes
where no ingredients were de-biased, indicating that these results explain most
of the projected changes, with the small differences that remain likely related
to interactions between ingredients. The large differences between the Eccel
proxy and the other proxies were caused by the instability--shear proxy reacting
to increases in instability without explicitly accounting for offsetting owing
to temperature or moisture changes. Changes in SHIP were driven mainly by
changes in the most-unstable-parcel mixing ratio, while in the Raupach proxy,
increases in hail-prone days owing to instability increases were offset by
changes in melting level height and temperature at 500 hPa.

\begin{figure*}[!ht]
    \includegraphics[width=\textwidth]{../../results/main/sig_drivers}
    \caption{\textbf{The main drivers of the projected changes.} All proxy
    ingredients are shown in Supplementary Figure \ref{SM-fig:drivers}. All
    plots are multimodel means. Plots show the difference in mean normalised
    annual hail-prone days (n=160 per grid point) between historical and the 3
    \degr{} epoch for unchanged ingredients, minus the difference with the given
    ingredient de-biased in the 3 \degr{} epoch. Red (blue) areas show where an
    ingredient added to (subtracted from) the projected change. Ingredients
    shown here are melting level height (MLH, a-c), mixed-layer convective
    available potential energy (MLCAPE, calculated using a well-mixed parcel on
    the lowest 100 hPa, d-f), most-unstable convective available potential
    energy (MUCAPE, calculated using the parcel with the largest equivalent
    potential temperature over the lowest 250 hPa, g-i), most-unstable-parcel
    mixing ratio (MUMR, j-l), and temperature at 500 hPa (T500, m-o). ``Sum''
    (p-r) shows sums across changes from all de-biased ingredients (column sums
    from Supplementary Figure \ref{SM-fig:drivers}) and ``Ref'' (s-u) shows the
    projected changes per proxy when no ingredients were de-biased. Columns show
    hail proxies and the colour scale is in annual hail days.}
    \label{fig:drivers}
\end{figure*}

\subsection*{Changes in hail-prone cropping periods}

Projected proportions of crop growing time considered hail-prone, for 26 crops
by world region, showed broad reductions in Africa and broad increases in Asia
(Figure \ref{fig:crop_changes}). We used a new metric, the hail-prone proportion
of cropping season (HPP), defined as the proportion of total cropping days
considered hail prone at a given location, in a given year and for a given crop,
based on monthly irrigated and rain-fed cropped areas \citep{Portmann_GBC_2010},
to measure relative hail occurrence hazard per crop. For the historical period,
the six crops with the highest hail hazard were sorghum, millet,
groundnuts/peanuts, rice, soybeans, and maize, with high hazard in the African
tropics and southeast Africa, southeast North America, and southeast South
America (Extended Data Figure \ref{ED-fig:historic_crop_proportions}). Warming
was projected to reduce HPP for these crops in these regions while increasing
HPP for crops grown in more poleward regions (Supplementary Figure
\ref{SM-fig:crop_changes_3C}). 

\begin{figure*}[!ht]
    \includegraphics[width=\textwidth]{../../results/main/crop_changes}
    \caption{\textbf{Distributions of significant changes in hail-prone crop
    proportion (HPP) by crop, epoch, and world region}. Changes are shown for
    Africa (a), Asia (b), Europe (c), North America (e), Oceania (f), and South
    America (g), and globally (d). Regions are defined as in Figure
    \ref{fig:future_changes_regional}. Changes are multimodel, multi-proxy mean
    changes in hail-prone proportion of cropping season (HPP), shown as a
    percentage of the multimodel, multi-proxy mean historical HPP. Significant
    changes are those for which at least 50\% of the model/proxy combinations
    agreed with the sign of the mean difference and also showed significant
    differences in the mean ($p < 0.05$ using a two-sided Welch's t-test, n=20
    years per epoch). Horizontal bars show medians, coloured boxes show
    interquartile ranges, whiskers show 10th-90th percentile ranges. The numbers
    of samples in each box plot are provided in Extended Data Table
    \ref{ED-tab:bar_ns}.}
    \label{fig:crop_changes}
\end{figure*}

In Africa, all crops were projected to experience fewer hail-prone days, with
regional increases not statistically significant (Extended Data Figure
\ref{ED-fig:crop_changes_africa}). In Asia (Extended Data Figure
\ref{ED-fig:crop_changes_asia}), there were a range of responses, with
decreasing hail hazard in India and southeastern China, but increases in HPP
across the north driving overall increases in hazard for many crops. Maize was
projected to experience greater hazard in southeastern China but lesser hazard
in the northeast, while HPP for wheat and rapeseed/canola increased in
northeastern China. In Europe and Western Asia, most significant changes were
increases, concentrated in a zonal band at around 60\degg{}N and in regions
around the European Alps, an area to the southeast of the Black Sea, and in
southern Iran (Extended Data Figure \ref{ED-fig:crop_changes_europe}). Increases
in HPP for rye were especially strong in Finland, Estonia, Latvia, and the
adjoining areas of Russia. In North America, there were significant increases
for barley and rye, which showed regional increases in HPP across central and
eastern USA, and Canada (Extended Data Figure
\ref{ED-fig:crop_changes_north_america}). For other crops, there were generally
decreases in HPP projected in the southeast, with increases projected in the
northwest and across northern Canada. In Oceania, barley was projected to have
increased hail hazard, albeit with a large range in projected changes, while HPP
decreased for all other crops. Significant decreases in HPP were concentrated in
Australia's northeast, while significant increases were in a small region of
southeast Australia and the South Island of New Zealand (Extended Data Figure
\ref{ED-fig:crop_changes_oceania}). In South America, all crops were projected
to have decreased overall hazard, except date palm and sugar beet which had few
significant changes (Extended Data Table \ref{ED-tab:bar_ns}). However, regional
changes show statistically significant increases in HPP for several crops in a
region of the southern Pampas and west to the Andes (Extended Data Figure
\ref{ED-fig:crop_changes_south_america}).

Localised monthly changes (Supplementary Figures
\ref{SM-fig:crop_lines_af}--\ref{SM-fig:crop_lines_india}) highlight that the
crops with the greatest projected increases in risk were those with winter
cropping periods, while those with the greatest reductions in risk were those
that grow across summer. For example, in China, potatoes crop from May to
September and were projected to have decreased risk, while wheat grows from
October to April and was projected to have increased risk (Supplementary Figure
\ref{SM-fig:crop_lines_as}). Uncertainty was higher for summer months, with
greater inter-model spread and with the sign of the change disagreeing between
proxies for some months.

\section*{Discussion}

We applied three hail proxies to eight global projections. Results were
divergent: the Raupach and SHIP proxies, that explicitly include offsetting
low-mid tropospheric temperature and moisture levels, respectively, projected
decreases in hail-prone condition frequency across the tropics, while the
instability--shear proxy of Eccel projected strong increases in these regions
owing to instability increases. This inconsistency may be explained by
offsetting of instability increases in the tropics: the Raupach proxy, in
particular, has a feature interaction where the melting level height affects the
relative importance of instability versus shear to the proxy
\cite{Raupach_MWR_2023} (Supplementary Section \ref{SM-sec:raupach_proxy}), and
thus is less sensitive to increased instability in the tropics. Driver analysis
shows this interaction, with the Raupach proxy less sensitive to instability in
the tropics than in the mid-latitudes (Figure \ref{fig:drivers}d).
Instability--shear proxies have a tendency to overestimate hail probability in
the tropics \cite{Raupach_MWR_2023}, which motivated development of the Raupach
proxy. The disagreement between proxy projections means there remains high
uncertainty on projections on hail hazard changes, particularly in the tropics.

We project broad poleward shifts in ensemble-mean hail-prone condition
occurrence frequency under 2 \degr{} and 3 \degr{} of warming, with decreases in
summer hail-prone day frequency and smaller increases in winter in some
mid-latitude regions including the USA, Europe, and Australia. The increases
were driven by changes in instability and offset by increases in low-mid
tropospheric temperature and moisture content. A sensitivity analysis showed
that winter crops were most likely to have increased hail hazard while summer
crops were most likely to experience reductions in hazard. We note that changes
in crop risk depend heavily on crop vulnerability which changes during growing
seasons \citep{Dhillon_CJPS_2021}. Similar to the differences between the Eccel
and Raupach/SHIP proxies, our results indicate that temperature-related effects
such as melting of hail \cite{Mahoney_NCC_2012} mean that changes in hail-prone
condition frequency may differ from those for all convective storms (regardless
of whether they produce hail), which are generally projected to increase with
warming \cite{Lepore_EF_2021}. We compare our results to previous studies in
Supplementary Section \ref{SM-sec:comparison_prev_studies}.

We used CMIP6 projections that include changes in atmospheric circulations, thus
avoiding a purely thermodynamic approach. Our projections align with projections
of poleward shifts in storm tracks \cite{Yin_GRL_2005, Tamarin_GRL_2017} and the
observed expansion of the tropics \cite{Heffernan_Nat_2016}. However, we note
that there is generally low confidence in how changes in dynamics affect extreme
events \cite{IPCC_2021_WGI_Ch_11}, and for the broader class of severe
convective storms (irrespective of hail occurrence) changes in reanalysis
periods \cite{Taszarek_npj_2021} can be of different sign to projected changes
\cite{Lepore_EF_2021}, which may be partly explained by uncertainty introduced
by changes in atmospheric circulation. Future work should consider
quantification of the relative importance of dynamic versus thermodynamic
changes on hail frequency globally. Proxies trained in one region cannot be
assumed to be perfectly applicable globally since storm properties differ by
location \cite{Brooks_AR_2003, Raupach_MWR_2023}. However, the Raupach proxy is
designed to take spatial variability in storm conditions into account and
performs reasonably across the Australian continent which contains a wide
variety of storm environments \cite{Raupach_npjCAS_2023}, and we validated the
ensemble-mean proxy results against published climatologies (Supplementary
Section \ref{SM-sec:proxy_validation}). The assumption of proxy stationarity in
future climates introduces uncertainty and should be tested. We did not consider
ocean areas because the proxies here were trained over land
\cite{Raupach_MWR_2023, Eccel_IJC_2012}, maritime hailstorms may exhibit
characteristics distinct from land storms \cite{Sari_JGRA_2025}, and there
remains uncertainty in the occurrence of hail in maritime storms
\citep{Knight_2001}.

Our results contribute to understanding climate impacts on global food
production. Most previous studies have concentrated on temperature,
precipitation, and CO2 changes, and neglect infrequent but high-impact extreme
weather \cite{Jagermeyr_NF_2021}. A limitation to our approach is our use of
stationary and relatively coarse crop data, so our analysis of crop changes form
a sensitivity study rather than projections for crop damage or yield. Suitable
growing regions and cropping periods may also shift poleward with warming
\cite{Franke_GCB_2022} with some positive impacts on yields
\cite{Jagermeyr_NF_2021}. Similar shifts in hail hazard may attenuate any
positive impact on crop yields in a warming world. For maize, an important
staple grown in tropical regions, a potential reduction in hail hazard would
only lessen the projected severe reduction in yield owing to increasing
temperatures \cite{Jagermeyr_NF_2021}. Importantly, crop damage from hail
depends on numerous factors including hailstone sizes and co-incident wind
strength \cite{Morgan_JAMC_1976}. Also, the timing of hail events within the
broad cropping season strongly influences possible crop damage, because crop
vulnerability to hail depends on the growth stage \cite{Dhillon_CJPS_2021}.
Future analyses should take projected changes in cropping season
\citep{Portmann_MZ_2025} and growth stages into account. 

We show projected changes in hail-prone day frequency, with proxy limitations
precluding examination of changes in hailstorm severity or hailstone size.
Increases in atmospheric instability (Supplementary Figure
\ref{SM-fig:ingredients_changes_1}) in regions with sufficient moisture
availability would generally be expected to increase generation of large
hailstones that could survive melting \cite{Raupach_NREE_2021}, so severity may
increase while frequency decreases. However, it remains difficult to draw
conclusions on hail size from environmental proxies, given complicated
offsetting and seasonally-dependent effects of ingredient changes
\cite{Mallinson_JC_2024}. A coincident decrease of small hail and increase of
large hail aligns has been projected for the end of the century in the USA
\cite{Gensini_npjCAS_2024}, pseudo-global-warming simulations in the USA have
shown a seasonal shift with increasing hailstone sizes in cold-season storms
\cite{Mallinson_JC_2024}, and end-of-century increases in hailstone size are
projected for some cities in Australia \cite{Raupach_GRL_2025}. While it is
likely that global severe hail projections would differ from the ``any hail''
projections shown here, the possibility of some areas experiencing compounding
risks with increased hail frequency in the cold season combined with increased
hailstone size \cite{Mallinson_JC_2024, Battaglioli_NG_2026} may produce a
pronounced risk to winter crops that merits further investigation.

\backmatter

\bmhead{Acknowledgements}

This research was supported by the Australian Government's National
Collaborative Research Infrastructure Strategy (NCRIS), with computational
resources provided by the National Computational Infrastructure (NCI) through
the National Computational Merit Allocation Scheme and the UNSW HPC Scheme (DOI:
10.26190/PMN5-7J50). THR acknowledges financial support from QBE Insurance. RP
acknowledges funding by the Swiss National Science Foundation (SNSF) Sinergia
grant CRSII\_201792.

\bmhead{Author contributions}

THR designed the study, performed the analyses, wrote the manuscript, and
created the figures. RP suggested the crop analysis. RP, CS, and SCS contributed
to design of analyses, interpretation of results, and editing of the paper.

\bmhead{Competing interests}

THR's position at UNSW Sydney is financially supported by QBE Insurance. The
authors declare no other competing financial or non-financial interests.

%TC:ignore
\bmhead{Figure captions}\mbox{}\par
\listoffigures

\bmhead{References}
%\bibliography{library}

\begingroup
\renewcommand{\refname}{\vspace{-0.5\baselineskip}}
\begin{thebibliography}{10}
\expandafter\ifx\csname url\endcsname\relax
  \def\url#1{\burl{#1}}\fi
\expandafter\ifx\csname urlprefix\endcsname\relax\def\urlprefix{URL }\fi
\providecommand{\bibinfo}[2]{#2}
\providecommand{\eprint}[2][]{\url{#2}}
\providecommand{\doi}[1]{\url{https://doi.org/#1}}
\bibcommenthead


\bibitem{Raupach_NREE_2021}
\bibinfo{author}{Raupach, T.~H.} \emph{et~al.}
\newblock \bibinfo{title}{The effects of climate change on hailstorms}.
\newblock \emph{\bibinfo{journal}{Nat. Rev. Earth Environ.}} \textbf{\bibinfo{volume}{2}}, \bibinfo{pages}{213--226} (\bibinfo{year}{2021}).

\bibitem{Bang_JAMC_2019}
\bibinfo{author}{Bang, S.~D.} \& \bibinfo{author}{Cecil, D.~J.}
\newblock \bibinfo{title}{Constructing a multifrequency passive microwave hail retrieval and climatology in the {GPM} domain}.
\newblock \emph{\bibinfo{journal}{J. Appl. Meteorol.}} \textbf{\bibinfo{volume}{58}}, \bibinfo{pages}{1889--1904} (\bibinfo{year}{2019}).

\bibitem{Prein_WCE_2018}
\bibinfo{author}{Prein, A.~F.} \& \bibinfo{author}{Holland, G.~J.}
\newblock \bibinfo{title}{Global estimates of damaging hail hazard}.
\newblock \emph{\bibinfo{journal}{Weather Clim. Extremes}} \textbf{\bibinfo{volume}{22}}, \bibinfo{pages}{10--23} (\bibinfo{year}{2018}).

\bibitem{Eyring_GMD_2016}
\bibinfo{author}{Eyring, V.} \emph{et~al.}
\newblock \bibinfo{title}{Overview of the {Coupled Model Intercomparison Project Phase 6 (CMIP6}) experimental design and organization}.
\newblock \emph{\bibinfo{journal}{Geosci. Model Dev.}} \textbf{\bibinfo{volume}{9}}, \bibinfo{pages}{1937--1958} (\bibinfo{year}{2016}).

\bibitem{Knight_2001}
\bibinfo{author}{Knight, C.~A.} \& \bibinfo{author}{Knight, N.~C.}
\newblock \bibinfo{title}{ in \textit{Hailstorms}} (ed.\bibinfo{editor}{Doswell, C.~A.}) \emph{\bibinfo{booktitle}{Severe Convective Storms}} \bibinfo{pages}{223--254} (\bibinfo{publisher}{American Meteorological Society}, \bibinfo{address}{Boston, MA}, \bibinfo{year}{2001}).

\bibitem{Brooks_AR_2003}
\bibinfo{author}{Brooks, H.~E.}, \bibinfo{author}{Lee, J.~W.} \& \bibinfo{author}{Craven, J.~P.}
\newblock \bibinfo{title}{The spatial distribution of severe thunderstorm and tornado environments from global reanalysis data}.
\newblock \emph{\bibinfo{journal}{Atmos. Res.}} \textbf{\bibinfo{volume}{67-68}}, \bibinfo{pages}{73--94} (\bibinfo{year}{2003}).
\newblock \bibinfo{note}{European Conference on Severe Storms 2002}.

\bibitem{Brooks_AR_2013}
\bibinfo{author}{Brooks, H.~E.}
\newblock \bibinfo{title}{Severe thunderstorms and climate change}.
\newblock \emph{\bibinfo{journal}{Atmos. Res.}} \textbf{\bibinfo{volume}{123}}, \bibinfo{pages}{129--138} (\bibinfo{year}{2013}).

\bibitem{Lin_JAS_2022}
\bibinfo{author}{Lin, Y.} \& \bibinfo{author}{Kumjian, M.~R.}
\newblock \bibinfo{title}{Influences of {CAPE} on hail production in simulated supercell storms}.
\newblock \emph{\bibinfo{journal}{J. Atmos. Sci.}} \textbf{\bibinfo{volume}{79}}, \bibinfo{pages}{179--204} (\bibinfo{year}{2022}).

\bibitem{Fischer_JAS_2025}
\bibinfo{author}{Fischer, J.}, \bibinfo{author}{Kunz, M.}, \bibinfo{author}{Lombardo, K.} \& \bibinfo{author}{Kumjian, M.~R.}
\newblock \bibinfo{title}{Hail trajectories in a wide spectrum of supercell-like updrafts}.
\newblock \emph{\bibinfo{journal}{J. Atmos. Sci.}} \textbf{\bibinfo{volume}{82}}, \bibinfo{pages}{1403 -- 1422} (\bibinfo{year}{2025}).

\bibitem{Raupach_MWR_2023}
\bibinfo{author}{Raupach, T.~H.}, \bibinfo{author}{Soderholm, J.}, \bibinfo{author}{Protat, A.} \& \bibinfo{author}{Sherwood, S.~C.}
\newblock \bibinfo{title}{An improved instability–shear hail proxy for {A}ustralia}.
\newblock \emph{\bibinfo{journal}{Mon. Weather Rev.}} \textbf{\bibinfo{volume}{151}}, \bibinfo{pages}{545--567} (\bibinfo{year}{2023}).

\bibitem{Tippett_CCCR_2015}
\bibinfo{author}{Tippett, M.~K.}, \bibinfo{author}{Allen, J.~T.}, \bibinfo{author}{Gensini, V.~A.} \& \bibinfo{author}{Brooks, H.~E.}
\newblock \bibinfo{title}{Climate and hazardous convective weather}.
\newblock \emph{\bibinfo{journal}{Curr. Clim. Change Rep.}} \textbf{\bibinfo{volume}{1}}, \bibinfo{pages}{60--73} (\bibinfo{year}{2015}).

\bibitem{Seeley_GRL_2015}
\bibinfo{author}{Seeley, J.~T.} \& \bibinfo{author}{Romps, D.~M.}
\newblock \bibinfo{title}{Why does tropical convective available potential energy ({CAPE}) increase with warming?}
\newblock \emph{\bibinfo{journal}{Geophys. Res. Lett.}} \textbf{\bibinfo{volume}{42}}, \bibinfo{pages}{10,429--10,437} (\bibinfo{year}{2015}).

\bibitem{Prein_NCC_2020}
\bibinfo{author}{Prein, A.~F.} \& \bibinfo{author}{Heymsfield, A.~J.}
\newblock \bibinfo{title}{Increased melting level height impacts surface precipitation phase and intensity}.
\newblock \emph{\bibinfo{journal}{Nat. Clim. Change}} \textbf{\bibinfo{volume}{10}}, \bibinfo{pages}{771--776} (\bibinfo{year}{2020}).

\bibitem{Mahoney_NCC_2012}
\bibinfo{author}{Mahoney, K.}, \bibinfo{author}{Alexander, M.~A.}, \bibinfo{author}{Thompson, G.}, \bibinfo{author}{Barsugli, J.~J.} \& \bibinfo{author}{Scott, J.~D.}
\newblock \bibinfo{title}{Changes in hail and flood risk in high-resolution simulations over {C}olorado's mountains}.
\newblock \emph{\bibinfo{journal}{Nat. Clim. Change}} \textbf{\bibinfo{volume}{2}}, \bibinfo{pages}{125--131} (\bibinfo{year}{2012}).

\bibitem{Trapp_GRL_2009}
\bibinfo{author}{Trapp, R.~J.}, \bibinfo{author}{Diffenbaugh, N.~S.} \& \bibinfo{author}{Gluhovsky, A.}
\newblock \bibinfo{title}{Transient response of severe thunderstorm forcing to elevated greenhouse gas concentrations}.
\newblock \emph{\bibinfo{journal}{Geophys. Res. Lett.}} \textbf{\bibinfo{volume}{36}}, \bibinfo{pages}{L01703} (\bibinfo{year}{2009}).

\bibitem{Radler_npjCAS_2019}
\bibinfo{author}{R\"adler, A.~T.}, \bibinfo{author}{Groenemeijer, P.~H.}, \bibinfo{author}{Faust, E.}, \bibinfo{author}{Sausen, R.} \& \bibinfo{author}{P\'u\v{c}ik, T.}
\newblock \bibinfo{title}{Frequency of severe thunderstorms across {E}urope expected to increase in the 21st century due to rising instability}.
\newblock \emph{\bibinfo{journal}{npj Clim. Atmos. Sci.}} \textbf{\bibinfo{volume}{2}}, \bibinfo{pages}{30} (\bibinfo{year}{2019}).

\bibitem{Battaglia_CS_2019}
\bibinfo{author}{Battaglia, M.}, \bibinfo{author}{Lee, C.}, \bibinfo{author}{Thomason, W.}, \bibinfo{author}{Fike, J.} \& \bibinfo{author}{Sadeghpour, A.}
\newblock \bibinfo{title}{Hail damage impacts on corn productivity: a review}.
\newblock \emph{\bibinfo{journal}{Crop Sci.}} \textbf{\bibinfo{volume}{59}}, \bibinfo{pages}{1--14} (\bibinfo{year}{2019}).

\bibitem{Dhillon_CJPS_2021}
\bibinfo{author}{Dhillon, G.~S.} \emph{et~al.}
\newblock \bibinfo{title}{Effects of simulated hail damage and foliar-applied recovery treatments on growth and grain yield of wheat, field pea, and dry bean crops}.
\newblock \emph{\bibinfo{journal}{Can. J. Plant Sci.}} \textbf{\bibinfo{volume}{101}}, \bibinfo{pages}{758--769} (\bibinfo{year}{2021}).

\bibitem{Changnon_JAMC_1971}
\bibinfo{author}{Changnon, S.~A.}
\newblock \bibinfo{title}{Hailfall characteristics related to crop damage}.
\newblock \emph{\bibinfo{journal}{J. Appl. Meteorol.}} \textbf{\bibinfo{volume}{10}}, \bibinfo{pages}{270 -- 274} (\bibinfo{year}{1971}).

\bibitem{Yue_PLOSONE_2019}
\bibinfo{author}{Yue, Y.}, \bibinfo{author}{Zhou, L.}, \bibinfo{author}{Zhu, A.-x.} \& \bibinfo{author}{Ye, X.}
\newblock \bibinfo{title}{Vulnerability of cotton subjected to hail damage}.
\newblock \emph{\bibinfo{journal}{PLOS ONE}} \textbf{\bibinfo{volume}{14}}, \bibinfo{pages}{1--21} (\bibinfo{year}{2019}).

\bibitem{Morgan_JAMC_1976}
\bibinfo{author}{Morgan, G.~M.} \& \bibinfo{author}{Towery, N.~G.}
\newblock \bibinfo{title}{On the role of strong winds in damage to crops by hail and its estimation with a simple instrument}.
\newblock \emph{\bibinfo{journal}{J. Appl. Meteorol.}} \textbf{\bibinfo{volume}{15}}, \bibinfo{pages}{891 -- 898} (\bibinfo{year}{1976}).

\bibitem{Sanchez_JAMC_1996}
\bibinfo{author}{S\'anchez, J.~L.} \emph{et~al.}
\newblock \bibinfo{title}{Crop damage: the hail size factor}.
\newblock \emph{\bibinfo{journal}{J. Appl. Meteorol.}} \textbf{\bibinfo{volume}{35}}, \bibinfo{pages}{1535 -- 1541} (\bibinfo{year}{1996}).

\bibitem{Dessens_GRL_1995}
\bibinfo{author}{Dessens, J.}
\newblock \bibinfo{title}{Severe convective weather in the context of a nighttime global warming}.
\newblock \emph{\bibinfo{journal}{Geophys. Res. Lett.}} \textbf{\bibinfo{volume}{22}}, \bibinfo{pages}{1241--1244} (\bibinfo{year}{1995}).

\bibitem{Botzen_REE_2010}
\bibinfo{author}{Botzen, W. J.~W.}, \bibinfo{author}{Bouwer, L.~M.} \& \bibinfo{author}{Bergh, J. C. J. M. v.~d.}
\newblock \bibinfo{title}{Climate change and hailstorm damage: empirical evidence and implications for agriculture and insurance}.
\newblock \emph{\bibinfo{journal}{Resour. Energy Econ.}} \textbf{\bibinfo{volume}{32}}, \bibinfo{pages}{341--362} (\bibinfo{year}{2010}).

\bibitem{Portmann_MZ_2025}
\bibinfo{author}{Portmann, R.} \emph{et~al.}
\newblock \bibinfo{title}{Earlier harvest but more hail -- hail risk to winter wheat in {S}witzerland since 1972}.
\newblock \emph{\bibinfo{journal}{Meteorol. Z.}} \bibinfo{pages}{--} (\bibinfo{year}{2026}).

\bibitem{Lepore_EF_2021}
\bibinfo{author}{Lepore, C.}, \bibinfo{author}{Abernathey, R.}, \bibinfo{author}{Henderson, N.}, \bibinfo{author}{Allen, J.~T.} \& \bibinfo{author}{Tippett, M.~K.}
\newblock \bibinfo{title}{Future global convective environments in {CMIP6} models}.
\newblock \emph{\bibinfo{journal}{Earth's Future}} \textbf{\bibinfo{volume}{9}}, \bibinfo{pages}{e2021EF002277} (\bibinfo{year}{2021}).

\bibitem{SPC_SHIP}
\bibinfo{author}{{NOAA SPC}}.
\newblock \bibinfo{title}{Significant hail parameter}.
\newblock \bibinfo{howpublished}{\url{https://www.spc.noaa.gov/exper/mesoanalysis/help/help_sigh.html}} (\bibinfo{year}{2022}).
\newblock \bibinfo{note}{National Oceanographic and Atmospheric Administration National Weather Service Storm Prediction Center, accessed 21 June 2022}.

\bibitem{Eccel_IJC_2012}
\bibinfo{author}{Eccel, E.}, \bibinfo{author}{Cau, P.}, \bibinfo{author}{Riemann-Campe, K.} \& \bibinfo{author}{Biasioli, F.}
\newblock \bibinfo{title}{Quantitative hail monitoring in an {A}lpine area: 35-year climatology and links with atmospheric variables}.
\newblock \emph{\bibinfo{journal}{Int. J. Climatol.}} \textbf{\bibinfo{volume}{3}}, \bibinfo{pages}{503--517} (\bibinfo{year}{2012}).

\bibitem{Portmann_GBC_2010}
\bibinfo{author}{Portmann, F.~T.}, \bibinfo{author}{Siebert, S.} \& \bibinfo{author}{D\"oll, P.}
\newblock \bibinfo{title}{{MIRCA2000—G}lobal monthly irrigated and rainfed crop areas around the year 2000: a new high-resolution data set for agricultural and hydrological modeling}.
\newblock \emph{\bibinfo{journal}{Global Biogeochem. Cy.}} \textbf{\bibinfo{volume}{24}} (\bibinfo{year}{2010}).

\bibitem{Yin_GRL_2005}
\bibinfo{author}{Yin, J.~H.}
\newblock \bibinfo{title}{A consistent poleward shift of the storm tracks in simulations of 21st century climate}.
\newblock \emph{\bibinfo{journal}{Geophys. Res. Lett.}} \textbf{\bibinfo{volume}{32}} (\bibinfo{year}{2005}).

\bibitem{Tamarin_GRL_2017}
\bibinfo{author}{Tamarin, T.} \& \bibinfo{author}{Kaspi, Y.}
\newblock \bibinfo{title}{The poleward shift of storm tracks under global warming: a {L}agrangian perspective}.
\newblock \emph{\bibinfo{journal}{Geophys. Res. Lett.}} \textbf{\bibinfo{volume}{44}}, \bibinfo{pages}{10,666--10,674} (\bibinfo{year}{2017}).

\bibitem{Heffernan_Nat_2016}
\bibinfo{author}{Heffernan, O.}
\newblock \bibinfo{title}{The mystery of the expanding tropics}.
\newblock \emph{\bibinfo{journal}{Nature}} \textbf{\bibinfo{volume}{530}}, \bibinfo{pages}{20--22} (\bibinfo{year}{2016}).

\bibitem{IPCC_2021_WGI_Ch_11}
\bibinfo{author}{Seneviratne, S.} \emph{et~al.}
\newblock \bibinfo{title}{ in \textit{Weather and climate extreme events in a changing climate}} (eds \bibinfo{editor}{Masson-Delmotte, V.} \emph{et~al.}) \emph{\bibinfo{booktitle}{Climate Change 2021: The Physical Science Basis. Contribution of Working Group I to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change}} \bibinfo{type}{book section}~\bibinfo{chapter}{11}, \bibinfo{pages}{1513--1765} (\bibinfo{publisher}{Cambridge University Press}, \bibinfo{address}{Cambridge, UK and New York, NY, USA}, \bibinfo{year}{2021}).
\newblock \urlprefix\url{https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_Chapter11.pdf}.

\bibitem{Taszarek_npj_2021}
\bibinfo{author}{Taszarek, M.}, \bibinfo{author}{Allen, J.~T.}, \bibinfo{author}{Marchio, M.} \& \bibinfo{author}{Brooks, H.~E.}
\newblock \bibinfo{title}{Global climatology and trends in convective environments from {ERA5} and rawinsonde data}.
\newblock \emph{\bibinfo{journal}{npj Clim. Atmos. Sci.}} \textbf{\bibinfo{volume}{4}}, \bibinfo{pages}{35} (\bibinfo{year}{2021}).

\bibitem{Raupach_npjCAS_2023}
\bibinfo{author}{Raupach, T.~H.}, \bibinfo{author}{Soderholm, J.~S.}, \bibinfo{author}{Warren, R.~A.} \& \bibinfo{author}{Sherwood, S.~C.}
\newblock \bibinfo{title}{Changes in hail hazard across {A}ustralia: 1979-2021}.
\newblock \emph{\bibinfo{journal}{npj Clim. Atmos. Sci.}} \textbf{\bibinfo{volume}{6}}, \bibinfo{pages}{143} (\bibinfo{year}{2023}).

\bibitem{Sari_JGRA_2025}
\bibinfo{author}{Sari, F.~P.} \& \bibinfo{author}{Lasher-Trapp, S.}
\newblock \bibinfo{title}{Hailstorm events over a maritime tropical region: storm environments and characteristics}.
\newblock \emph{\bibinfo{journal}{J. Geophys. Res.-Atmos.}} \textbf{\bibinfo{volume}{130}}, \bibinfo{pages}{e2024JD042718} (\bibinfo{year}{2025}).
\newblock \bibinfo{note}{E2024JD042718 2024JD042718}.

\bibitem{Jagermeyr_NF_2021}
\bibinfo{author}{J\"agermeyr, J.} \emph{et~al.}
\newblock \bibinfo{title}{Climate impacts on global agriculture emerge earlier in new generation of climate and crop models}.
\newblock \emph{\bibinfo{journal}{Nat. Food}} \textbf{\bibinfo{volume}{2}}, \bibinfo{pages}{873--885} (\bibinfo{year}{2021}).

\bibitem{Franke_GCB_2022}
\bibinfo{author}{Franke, J.~A.} \emph{et~al.}
\newblock \bibinfo{title}{Agricultural breadbaskets shift poleward given adaptive farmer behavior under climate change}.
\newblock \emph{\bibinfo{journal}{Glob. Change Biol.}} \textbf{\bibinfo{volume}{28}}, \bibinfo{pages}{167--181} (\bibinfo{year}{2022}).

\bibitem{Mallinson_JC_2024}
\bibinfo{author}{Mallinson, H.}, \bibinfo{author}{Lasher-Trapp, S.}, \bibinfo{author}{Trapp, J.}, \bibinfo{author}{Woods, M.} \& \bibinfo{author}{Orendorf, S.}
\newblock \bibinfo{title}{Hailfall in a possible future climate using a pseudo-global warming approach: hail characteristics and mesoscale influences}.
\newblock \emph{\bibinfo{journal}{J. Climate}} \textbf{\bibinfo{volume}{37}}, \bibinfo{pages}{527 -- 549} (\bibinfo{year}{2024}).

\bibitem{Gensini_npjCAS_2024}
\bibinfo{author}{Gensini, V.~A.} \emph{et~al.}
\newblock \bibinfo{title}{Hailstone size dichotomy in a warming climate}.
\newblock \emph{\bibinfo{journal}{npj Clim. Atmos. Sci.}} \textbf{\bibinfo{volume}{7}}, \bibinfo{pages}{185} (\bibinfo{year}{2024}).

\bibitem{Raupach_GRL_2025}
\bibinfo{author}{Raupach, T.~H.} \& \bibinfo{author}{Aldridge, J.}
\newblock \bibinfo{title}{Changes in hail damage potential in major {A}ustralian cities with global warming}.
\newblock \emph{\bibinfo{journal}{Geophys. Res. Lett.}} \textbf{\bibinfo{volume}{52}}, \bibinfo{pages}{e2025GL117676} (\bibinfo{year}{2025}).
\newblock \bibinfo{note}{E2025GL117676 2025GL117676}.

\bibitem{Battaglioli_NG_2026}
\bibinfo{author}{Battaglioli, F.}, \bibinfo{author}{Taszarek, M.}, \bibinfo{author}{Groenemeijer, P.}, \bibinfo{author}{P\'u\v{c}ik, T.} \& \bibinfo{author}{R\"adler, A.}
\newblock \bibinfo{title}{Contrasting trends in very large hail events and related economic losses across the globe}.
\newblock \emph{\bibinfo{journal}{Nature Geoscience}} \textbf{\bibinfo{volume}{19}}, \bibinfo{pages}{52--58} (\bibinfo{year}{2026}).
\newblock \urlprefix\url{https://doi.org/10.1038/s41561-025-01868-0}.

\end{thebibliography}
\endgroup

\section*{Methods}
\label{sec:methods}

\subsection*{Data}

A filtering approach was used to select models from the Coupled Model
Intercomparison Project Phase 6 (CMIP6) \cite{Eyring_GMD_2016}. We selected
models that contained variables required to calculate convective indices: air
temperature at the surface (\texttt{tas}) and by model level (\texttt{ta}), wind
vectors at the surface (\texttt{uas} and \texttt{vas}) and by level (\texttt{ua}
and \texttt{va}), specific humidity at the surface (\texttt{huss}) and by level
(\texttt{hus}), and surface pressure (\texttt{ps}). We filtered for models with
a temporal resolution at least as fine as six-hourly (those with ``table IDs''
of \texttt{3hr} or \texttt{6hrLev}), and models that were available for both
historical and SSP5-8.5 experiments (``experiment IDs'' of \texttt{historical}
or \texttt{ssp585}). Further, the models had to be available in the National
Computational Infrastructure (NCI) node of the Earth System Grid Federation
(ESGF), and had to cover the required epochs. The resulting CMIP6 models, that
we used here \cite{CMCC-CM2-SR5_historical, CMCC-CM2-SR5_ssp585,
CMCC-ESM2_historical, CMCC-ESM2_ssp585, CNRM-CM6-1_historical,
CNRM-CM6-1_ssp585, EC-Earth3_historical, EC-Earth3_ssp585, NASA-GISS_historical,
NASA-GISS_ssp585, MIROC_historical, MIROC_ssp585, MPI-ESM1-2-HR_historical,
MPI-ESM1-2-HR_ssp585, MRI-ESM2-0_historical, MRI-ESM2-0_ssp585}, are detailed in
Supplementary Table \ref{SM-tab:model_details}. Model data were used at 6-hourly
temporal resolution. If model orography was available in the \texttt{orog}
variable, it was used; if not, the orography of the historical runs of
CNRM-CM6-1 (ensemble r1i1p1f2) was interpolated onto the model grid and used
instead \cite{Bracegirdle_ASL_2020}. Reanalyses were European Centre for
Medium-range Weather Forecasts (ECMWF) reanalysis 5 (ERA5) data
\cite{Hersbach_QJRMS_2020} on pressure levels. To match the CMIP6 model
characteristics, we used global ERA5 data at 00, 06, 12, and 18 UTC for each day
from 1980 to 1999, interpolated to 1$^{\circ}$$\times$1$^{\circ}$ resolution.
Cropping periods for each 1$^{\circ}$$\times$1$^{\circ}$ grid point were
calculated as the union of all monthly cropping periods, per crop, from
MIRCA2000 \citep{Portmann_GBC_2010} data at 0.5$^{\circ}$$\times$0.5$^{\circ}$
resolution. MIRCA2000 provides global cropping months for 26 crops for the year
2000; we considered both rain-fed and irrigated crops. The cropping season is
defined at a monthly time scale. If a month belongs to the cropping season of a
particular crop at a particular location in MIRCA2000, all days of this month
are considered as cropping days. Crop vulnerability to hail depends strongly on
the crop growth stage \citep{Dhillon_CJPS_2021}. Here, we used the full cropping
period including phases of low and high vulnerability.

\subsection*{Calculation of convective parameters}

Convective parameters were calculated as described for the proxy of Raupach et
al., 2023 \cite{Raupach_MWR_2023}, for each CMIP6 dataset at its native
resolution and for downscaled ERA5 data. For each CMIP6 model, annual and
seasonal statistics were calculated, then all statistics were interpolated onto
a 1$^{\circ}$$\times$1$^{\circ}$ grid for comparison.

\subsection*{Application of hail proxies}

We applied three hail-specific instability-shear proxies -- Raupach, Eccel, and
SHIP -- to CMIP6 and ERA5 data. The proxies were, respectively, the Raupach
proxy, a modified version of the proxy in Raupach et al., 2023
\cite{Raupach_MWR_2023}, the Eccel proxy of Eccel et al., 2012
\cite{Eccel_IJC_2012}, and SHIP, a threshold of 0.1 on the Significant Hail
Parameter \cite{SPC_SHIP}. The proxies are described in detail in Supplementary
Section \ref{SM-sec:proxy-formulas}. Proxies results were masked to land areas
in recognition that the proxies were trained on land-based reports and no
surface-based climatologies are available for ocean areas. Proxy outputs (binary
hail-prone or not-hail-prone) were collated into annual hail-prone days.

\subsection*{Proxy normalisation}

To give proxies equal weighting when calculating multimodel, multi-proxy means,
annual hail-prone days were normalised per model and proxy. The three proxies
produced binary outputs, classifying each day as hail prone or not hail prone.
Annual hail-prone days were the sum of all hail-prone days per year per
location. To account for differences between the proxies and between models, and
to allow each proxy to have the same weight when calculating multimodel,
multi-proxy means, annual hail-prone days (AHPD) were normalised per proxy and
per model, such that

\begin{equation}
\textrm{AHPD}_{m,p,i,j,y} = \frac{\textrm{AHPD}_{m,p,i,j,y}}{\max\left([\textrm{AHPD}_{m,p,i,j,y}\;\forall\; i, j, y]\right)} \times 100,
\end{equation}

\noindent where $m$, $p$, $i$, $j$, $y$ are indices for model, proxy, longitude,
latitude, and year, respectively.

\subsection*{Per-degree framework}

The historical period used for each model was 1980--1999. The epochs that
represented 2 \degr{} and 3 \degr{} warming compared to the historical period
were determined per model using 20-year running means of monthly global average
temperature anomalies (Supplementary Figure \ref{SM-fig:epochs}).

\subsection*{Calculation of drivers}

For each hail proxy ingredient, de-biased versions of the 3 \degr{} epoch were
calculated using \texttt{python-cmethods} \cite{Schwertfeger_2024} using the
quantile-mapping method with 100 quantiles and the historical period as the
baseline. Annual hail-prone days in the de-biased datasets were normalised by
the same factor used in the non-de-biased data.

\bmhead{Data availability}

MIRCA2000 data are available under CC-BY at
\url{https://doi.org/10.5281/zenodo.7422506} \cite{Portmann_MIRCA_2022}. ERA5
data are available under CC-BY at
\url{https://www.ecmwf.int/en/forecasts/dataset/ecmwf-reanalysis-v5}
\cite{ERA5_data}. CMIP6 data are available via
\url{https://pcmdi.llnl.gov/CMIP6/} \cite{CMCC-CM2-SR5_historical,
CMCC-CM2-SR5_ssp585, CMCC-ESM2_historical, CMCC-ESM2_ssp585,
CNRM-CM6-1_historical, CNRM-CM6-1_ssp585, EC-Earth3_historical,
EC-Earth3_ssp585, NASA-GISS_historical, NASA-GISS_ssp585, MIROC_historical,
MIROC_ssp585, MPI-ESM1-2-HR_historical, MPI-ESM1-2-HR_ssp585,
MRI-ESM2-0_historical, MRI-ESM2-0_ssp585} with licenses shown in Supplementary
Table \ref{SM-tab:CMIP6_data_refs}.

\bmhead{Code availability}

Convective indices were calculated using \texttt{xarray\_parcel} by T. H.
Raupach (\url{https://doi.org/10.5281/zenodo.16924288})
\cite{Raupach_xarray_2025}. Warming levels were calculated using code by T. H.
Raupach (\url{https://doi.org/10.5281/zenodo.10785698})
\cite{Raupach_warming_levels_2024}. De-biasing code was \texttt{python-cmethods}
by B. T. Schwertfeger (\url{https://doi.org/10.5281/zenodo.12168002})
\cite{Schwertfeger_2024}. All study code is archived at
\url{https://doi.org/10.5281/zenodo.15099057}
\cite{Raupach_zenodo_archive_2026} and available under CC-BY-NC; this article
used version v1.0.4 of the code.

\bmhead{Methods-only references}
\begingroup
\renewcommand{\refname}{\vspace{-0.5\baselineskip}}
\begin{thebibliography}{10}
\expandafter\ifx\csname url\endcsname\relax
  \def\url#1{\burl{#1}}\fi
\expandafter\ifx\csname urlprefix\endcsname\relax\def\urlprefix{URL }\fi
\providecommand{\bibinfo}[2]{#2}
\providecommand{\eprint}[2][]{\url{#2}}
\providecommand{\doi}[1]{\url{https://doi.org/#1}}
\bibcommenthead

\setcounter{NAT@ctr}{42}
\setcounter{enumiv}{42}

\bibitem{CMCC-CM2-SR5_historical}
\bibinfo{author}{Lovato, T.} \& \bibinfo{author}{Peano, D.}
\newblock \bibinfo{title}{{CMCC CMCC-CM2-SR5 model output prepared for CMIP6 CMIP historical}} (\bibinfo{year}{2020}).
\newblock \urlprefix\url{https://doi.org/10.22033/ESGF/CMIP6.3825}.

\bibitem{CMCC-CM2-SR5_ssp585}
\bibinfo{author}{Lovato, T.} \& \bibinfo{author}{Peano, D.}
\newblock \bibinfo{title}{{CMCC CMCC-CM2-SR5 model output prepared for CMIP6 ScenarioMIP ssp585}} (\bibinfo{year}{2020}).
\newblock \urlprefix\url{https://doi.org/10.22033/ESGF/CMIP6.3896}.

\bibitem{CMCC-ESM2_historical}
\bibinfo{author}{Lovato, T.}, \bibinfo{author}{Peano, D.} \& \bibinfo{author}{Butensch\"{o}n, M.}
\newblock \bibinfo{title}{{CMCC CMCC-ESM2 model output prepared for CMIP6 CMIP historical}} (\bibinfo{year}{2021}).
\newblock \urlprefix\url{https://doi.org/10.22033/ESGF/CMIP6.13195}.

\bibitem{CMCC-ESM2_ssp585}
\bibinfo{author}{Lovato, T.}, \bibinfo{author}{Peano, D.} \& \bibinfo{author}{Butensch\"{o}n, M.}
\newblock \bibinfo{title}{{CMCC CMCC-ESM2 model output prepared for CMIP6 ScenarioMIP ssp585}} (\bibinfo{year}{2021}).
\newblock \urlprefix\url{https://doi.org/10.22033/ESGF/CMIP6.13259}.

\bibitem{CNRM-CM6-1_historical}
\bibinfo{author}{Voldoire, A.}
\newblock \bibinfo{title}{{CMIP6 simulations of the CNRM-CERFACS based on CNRM-CM6-1 model for CMIP experiment historical}} (\bibinfo{year}{2018}).
\newblock \urlprefix\url{https://doi.org/10.22033/ESGF/CMIP6.4066}.

\bibitem{CNRM-CM6-1_ssp585}
\bibinfo{author}{Voldoire, A.}
\newblock \bibinfo{title}{{CNRM-CERFACS CNRM-CM6-1 model output prepared for CMIP6 ScenarioMIP ssp585}} (\bibinfo{year}{2019}).
\newblock \urlprefix\url{https://doi.org/10.22033/ESGF/CMIP6.4224}.

\bibitem{EC-Earth3_historical}
\bibinfo{author}{{EC-Earth Consortium (EC-Earth)}}.
\newblock \bibinfo{title}{{EC-Earth-Consortium EC-Earth3 model output prepared for CMIP6 CMIP historical}} (\bibinfo{year}{2019}).
\newblock \urlprefix\url{https://doi.org/10.22033/ESGF/CMIP6.4700}.

\bibitem{EC-Earth3_ssp585}
\bibinfo{author}{{EC-Earth Consortium (EC-Earth)}}.
\newblock \bibinfo{title}{{EC-Earth-Consortium EC-Earth3 model output prepared for CMIP6 ScenarioMIP ssp585}} (\bibinfo{year}{2019}).
\newblock \urlprefix\url{https://doi.org/10.22033/ESGF/CMIP6.4912}.

\bibitem{NASA-GISS_historical}
\bibinfo{author}{{NASA Goddard Institute for Space Studies (NASA/GISS)}}.
\newblock \bibinfo{title}{{NASA-GISS GISS-E2.1G model output prepared for CMIP6 CMIP historical}} (\bibinfo{year}{2018}).
\newblock \urlprefix\url{https://doi.org/10.22033/ESGF/CMIP6.7127}.

\bibitem{NASA-GISS_ssp585}
\bibinfo{author}{{NASA Goddard Institute for Space Studies (NASA/GISS)}}.
\newblock \bibinfo{title}{{NASA-GISS GISS-E2.1G model output prepared for CMIP6 ScenarioMIP ssp585}} (\bibinfo{year}{2020}).
\newblock \urlprefix\url{https://doi.org/10.22033/ESGF/CMIP6.7460}.

\bibitem{MIROC_historical}
\bibinfo{author}{Tatebe, H.} \& \bibinfo{author}{Watanabe, M.}
\newblock \bibinfo{title}{{MIROC MIROC6 model output prepared for CMIP6 CMIP historical}} (\bibinfo{year}{2018}).
\newblock \urlprefix\url{https://doi.org/10.22033/ESGF/CMIP6.5603}.

\bibitem{MIROC_ssp585}
\bibinfo{author}{Shiogama, H.}, \bibinfo{author}{Abe, M.} \& \bibinfo{author}{Tatebe, H.}
\newblock \bibinfo{title}{{MIROC MIROC6 model output prepared for CMIP6 ScenarioMIP ssp585}} (\bibinfo{year}{2019}).
\newblock \urlprefix\url{https://doi.org/10.22033/ESGF/CMIP6.5771}.

\bibitem{MPI-ESM1-2-HR_historical}
\bibinfo{author}{Jungclaus, J.} \emph{et~al.}
\newblock \bibinfo{title}{{MPI-M MPI-ESM1.2-HR model output prepared for CMIP6 CMIP historical}} (\bibinfo{year}{2019}).
\newblock \urlprefix\url{https://doi.org/10.22033/ESGF/CMIP6.6594}.

\bibitem{MPI-ESM1-2-HR_ssp585}
\bibinfo{author}{Schupfner, M.} \emph{et~al.}
\newblock \bibinfo{title}{{DKRZ MPI-ESM1.2-HR model output prepared for CMIP6 ScenarioMIP ssp585}} (\bibinfo{year}{2019}).
\newblock \urlprefix\url{https://doi.org/10.22033/ESGF/CMIP6.4403}.

\bibitem{MRI-ESM2-0_historical}
\bibinfo{author}{Yukimoto, S.} \emph{et~al.}
\newblock \bibinfo{title}{{MRI MRI-ESM2.0 model output prepared for CMIP6 CMIP historical}} (\bibinfo{year}{2019}).
\newblock \urlprefix\url{https://doi.org/10.22033/ESGF/CMIP6.6842}.

\bibitem{MRI-ESM2-0_ssp585}
\bibinfo{author}{Yukimoto, S.} \emph{et~al.}
\newblock \bibinfo{title}{{MRI MRI-ESM2.0 model output prepared for CMIP6 ScenarioMIP ssp585}} (\bibinfo{year}{2019}).
\newblock \urlprefix\url{https://doi.org/10.22033/ESGF/CMIP6.6929}.

\bibitem{Bracegirdle_ASL_2020}
\bibinfo{author}{Bracegirdle, T.~J.} \emph{et~al.}
\newblock \bibinfo{title}{Twenty first century changes in {Antarctic and Southern Ocean} surface climate in {CMIP6}}.
\newblock \emph{\bibinfo{journal}{Atmos. Sci. Lett.}} \textbf{\bibinfo{volume}{21}}, \bibinfo{pages}{e984} (\bibinfo{year}{2020}).

\bibitem{Hersbach_QJRMS_2020}
\bibinfo{author}{Hersbach, H.} \emph{et~al.}
\newblock \bibinfo{title}{The {ERA5} global reanalysis}.
\newblock \emph{\bibinfo{journal}{Q. J. Roy. Meteor. Soc.}} \textbf{\bibinfo{volume}{146}}, \bibinfo{pages}{1999--2049} (\bibinfo{year}{2020}).

\bibitem{Schwertfeger_2024}
\bibinfo{author}{Schwertfeger, B.~T.}
\newblock \bibinfo{title}{btschwertfeger/python-cmethods: v2.3.0} (\bibinfo{year}{2024}).
\newblock \urlprefix\url{https://doi.org/10.5281/zenodo.12168002}.

\bibitem{Portmann_MIRCA_2022}
\bibinfo{author}{Portmann, F.~T.}, \bibinfo{author}{Siebert, S.} \& \bibinfo{author}{D\"oll, P.}
\newblock \bibinfo{title}{Mirca2000} (\bibinfo{year}{2022}).
\newblock \urlprefix\url{https://doi.org/10.5281/zenodo.7422506}.

\bibitem{ERA5_data}
\bibinfo{author}{Hersbach, H.} \emph{et~al.}
\newblock \bibinfo{title}{{ERA5} hourly data on pressure levels from 1979 to present} (\bibinfo{year}{2018}).
\newblock \bibinfo{note}{Copernicus Climate Change Service (C3S) Climate Data Store (CDS).}

\bibitem{Raupach_warming_levels_2024}
\bibinfo{author}{Raupach, T.~H.}
\newblock \bibinfo{title}{Code to calculate warming levels from {CMIP6} and {CMIP5}} (\bibinfo{year}{2024}).
\newblock \urlprefix\url{https://doi.org/10.5281/zenodo.10785698}.

\bibitem{Raupach_zenodo_archive_2026}
\bibinfo{author}{Raupach, T.}
\newblock \bibinfo{title}{traupach/future\_hail\_global: v1.0.4} (\bibinfo{year}{2026}).
\newblock \urlprefix\url{https://doi.org/10.5281/zenodo.15099057}.

\end{thebibliography}
\endgroup
%TC:endignore

\end{document}