\documentclass[pdflatex, sn-nature]{sn-jnl}

\usepackage{fullpage}
\usepackage{amsmath}
\usepackage{url}
\usepackage{booktabs}
\usepackage{placeins}
\usepackage{xr}

\usepackage[font=small]{caption}

%\urlstyle{same}
\newcommand{\degr}{$^{\circ{}}$C}

\renewcommand{\figurename}{Supplementary Figure}
\renewcommand\refname{Supplementary References}

\externaldocument[ED-]{../extended_data/ext_data}
\externaldocument[main-]{../main/future_hail}

\makeatletter
\def\ps@plain{%
  \let\@mkboth\@gobbletwo
  \let\@oddhead\@empty
  \let\@evenhead\@empty
  \def\@oddfoot{\hfill\thepage\hfill}%
  \let\@evenfoot\@oddfoot
}
\makeatother

\begin{document}
\setcounter{page}{1}
\pagestyle{plain}

<<loadResults, echo=FALSE, results=FALSE, message=FALSE>>=
library(rjson)
results_proxy_update = fromJSON(file='../../results/results_proxy_update.json')
library(tidyverse)
library(xtable)
@

\tableofcontents

%\newpage
\section*{Supplementary Material Contents}

This supplementary material contains:

\begin{itemize}
\item Section \ref{sec:proxy_validation}: A validation of proxy climatologies via comparison with published climatologies.
\item Section \ref{sec:cases}: Case studies of hail-prone day anomalies for known damaging hail events.
\item Section \ref{sec:projected_ingredients}: Projected changes in proxy ingredients.
\item Section \ref{sec:comparison_prev_studies}: A detailed comparison of our results to previous studies.
\item Section \ref{sec:supp_figures}: Supplementary tables and figures: Supplementary Table \ref{tab:model_details} and Supplementary Figures \ref{fig:anoms_India_2015}--\ref{fig:epochs}.
\item Section \ref{sec:proxy-formulas}: A detailed description of the proxies used in this study.
\end{itemize}

\section{Validation of proxy climatologies}
\label{sec:proxy_validation}

We used normalised proxies because individual model/proxy combinations produced
varying numbers of hail-prone days (Extended Data Figure
\ref{ED-fig:historical_annual_means}). The three proxies we used were trained
locally in Australia (Raupach), Italy (Eccel), and the USA (SHIP), which raises
the question of whether they can reasonably be applied globally. In this section
we compare, in detail, the proxy ensemble output we use in this work to
published climatologies by world region. For global climatologies we compared to
the proxy-based climatology of Prein \& Holland, 2018 (\cite{Prein_WCE_2018},
hereafter PH18) and the satellite-based climatology of Bang \& Cecil, 2019
(\cite{Bang_JAMC_2019}, hereafter BC19) while noting that both these global
climatologies are for severe or large hail, and the proxies we use in this study
are chosen to detect \textit{any} hail-prone conditions (with the low threshold
we used for POH). We thus expect some differences with these previous global
climatologies. There are no ``perfect'' hail observations because hail is small
in scale and relatively rare, radars and observations networks have limited
spatial coverage, reports contain non-meteorological biases, and there are
significant uncertainties in linking large-scale environments (using proxies) or
observations aloft by satellite or radar to surface hail occurrence
\citep{Raupach_NREE_2021}. The climatological studies we compared to included
all available data sources including proxies, radar, satellite, and
observations/reports. We used as many studies as possible for each region, to
incorporate local knowledge, observations, and model training into our global
proxy validation. Differences in geographical supports, observation techniques,
reporting standards, and the mixture of direct and indirect methods to estimate
hail occurrence in the literature mean that it is not feasible to compare
absolute numbers of hail occurrences or hail-prone days between climatologies.
Instead, we focused on whether there is agreement in relative hail activity by
region. Regional commentary and comparisons are shown in the following
subsections, in which we use the region and subregions definitions of the United
Nations geoscheme \citep{UN_geoscheme}.

\subsection{Areas referred to in the main text}
\label{sec:regions}

In the main paper, we use the following shorthand definitions to refer to the
following regions of the United Nations geoscheme \citep{UN_geoscheme}. ``Asia''
refers to Southern, Eastern, Northern, and northern South-eastern Asia as shown
in Figure \ref{fig:proxy_climatology_asia}; ``Oceania'' refers to Oceania and
southern South-eastern Asia as shown in Figure
\ref{fig:proxy_climatology_oceania}; ``North America'' refers to Northern
America, Central America, and the Caribbean, as shown in Figure
\ref{fig:proxy_climatology_north_america}; ``South America'' refers to South
America as shown in Figure \ref{fig:proxy_climatology_south_america}; ``Europe''
refers to Europe, Northern Africa, Western Asia, and Iran as shown in Figure
\ref{fig:proxy_climatology_europe}; and ``Africa'' refers to Africa as shown in
Figure \ref{fig:proxy_climatology_africa}.

\subsection{Southern, Eastern, Northern, and northern South-eastern Asia}

\begin{figure}[h]
\includegraphics[width=\textwidth]{../../results/supplementary/proxy_climatology_asia}
\caption{Mean and standard deviation of normalised annual hail-prone days across
the model-proxy ensemble for the historical period, including CMIP6 models and
ERA5 reanalysis, for Southern, Eastern, Northern, and northern South-eastern
Asia. n=180 per grid point. Solid black lines show coastlines and political
borders; dotted black lines show provincial boundaries for some countries.}
\label{fig:proxy_climatology_asia}
\end{figure}

In Asia, the proxy ensemble (Figure \ref{fig:proxy_climatology_asia}) highlights
the southern flank of the Himalaya and particularly its southeastern end as the
most hail-prone region, with another hotspot in southern China, and low hail
probability across the Tibetan plateau. This pattern matches a satellite severe
hail climatology \citep{Bang_JAMC_2019} and is similar to the severe hail
climatology of PH18, except that study shows another hotspot in the northeast of
Pakistan which is not matched by the proxy ensemble or by BC19. Regional studies
confirm that the northwestern Himalaya \citep{Bhat_NH_2024}, North, Northeast,
and East India \citep{Rao_NH_2025}, Northern Thailand \citep{Mahavik_NH_2025},
and Southwestern China \citep{Li_JAMC_2018} are hail hotspots. Hail is also
reported across some parts of Central India \citep{Rao_NH_2025,
Ravindren_NH_2025} where satellite and proxy products show only moderate hail
probability. Hail in Western Siberia is infrequent but does occur in the regions
highlighted by the proxy ensemble \citep{Gorbatenko_RMH_2020}. Station-based
climatologies in China show high hail occurrence over the Tibetan Plateau
\citep{Zhang_JAMC_2008, Li_JAMC_2018}, disagreeing with both proxy and satellite
studies. In summary, the proxy ensemble agrees well with published climatologies
for Southern, Eastern, Northern, and northern South-eastern Asia, except for the
Tibetan Plateau where the ensemble agrees with satellite and proxy climatologies
but disagrees with station data.

\FloatBarrier

\subsection{Oceania and southern South-eastern Asia}
\label{sec:oceania}

\begin{figure}[h]
\includegraphics[width=\textwidth]{../../results/supplementary/proxy_climatology_oceania}
\caption{As for Figure \ref{fig:proxy_climatology_asia} but for Oceania.}
\label{fig:proxy_climatology_oceania}
\end{figure}

In Oceania, the proxy ensemble (Figure \ref{fig:proxy_climatology_oceania})
shows high hail probability on the mid-eastern coast of Australia with higher
hail probability in the country's northwest and low probability in the arid
centre, some hail activity in New Zealand's North Island but lower probabilities
in the South Island, and moderate hail activity in Indonesia.
PH18 and BC19 both show regions of higher
severe hail probability on the mid-eastern and northern coasts of Australia and
moderate probabilities in Australia's northwest. PH18's results
suggest the possibility of hail activity in Australia's southwest and western
interior, where the ensemble generally shows low probability (although some
ensemble members show hail activity in the far southwest). BC19
shows low but non-zero severe hail probability across the western Maritime
Continent, agreeing with the ensemble but disagreeing with
PH18. The ensemble and PH18 agree on the North
Island of New Zealand showing higher hail probability than the South Island.
Regional studies confirm the hail occurrence peak on Australia's east coast
\citep{Raupach_npjCAS_2023, Brook_MWR_2024} and the possibility of a hail
hotspot in the southwest \citep{Raupach_npjCAS_2023, Brook_MWR_2024,
Bedka_JAMC_2018}, while hail in Australia's tropics is subject to uncertainty
\citep{Raupach_MWR_2023, Bedka_JAMC_2018, Prein_WCE_2018}. In New Zealand,
hailstorm occurrence is recorded as increasing towards the west and south
\citep{Steiner_NZJGG_1989}, but recent data are scarce. In Indonesia there are
few studies but damaging hailstorms do occur \citep{Sari_JGRA_2025}. Overall,
the proxy ensemble agrees well with the locations of known hail hotspots in
Oceania and southern South-eastern Asia.

\FloatBarrier

\subsection{Northern America, Central America, and the Caribbean}

\begin{figure}[h]
\includegraphics[width=\textwidth]{../../results/supplementary/proxy_climatology_north_america}
\caption{As for Figure \ref{fig:proxy_climatology_asia} but for Northern
America, Central America, and the Caribbean.}
\label{fig:proxy_climatology_north_america}
\end{figure}

The proxy ensemble (Figure \ref{fig:proxy_climatology_north_america}) shows
hail-prone areas in Northern America as lying to the east of the Rocky Mountains
with the highest occurrence of hail-prone conditions in the southeast United
States of America (USA), along the Gulf of Mexico and eastern Florida. In
addition, the ensemble shows hail-prone conditions extending north into Canada
with the furthest extension in Alberta, and extending south into Central
America, with a thin region of increased probability along the west coast of
Mexico. The severe hail climatology of PH18 highlights a similar overall region
of risk and also shows increased hail risk in Mexico's west, albeit a little
further inland. However, PH18 has the highest probability area in the USA
extending further north across the Great Plains than the proxy ensemble.
Satellite-based detections also highlight similar regions as the proxy ensemble,
but put the greatest occurrence across the US Great Plains and Cuba
\citep{Bang_JAMC_2019}. Extended Data Figure
\ref{ED-fig:historical_annual_means} shows that the latitude of the peak in
hail-prone conditions changes by proxy and model in our results. Regional
climatologies confirm that the most hail-prone areas of the United States is the
Great Plains east of the Rocky Mountains, and that there is a strong east-west
divide with little hail occurrence to the west of the Rocky Mountains
\citep{Cintineo_WF_2012, Allen_EJSSM_2015, Allen_JAMES_2015, Murillo_MWR_2021}.
A radar-based climatology shows outlier hotspots in Florida and the eastern
sides of Georgia and South Carolina \citep{Cintineo_WF_2012}, and hail reports
exist in most areas east of the Rocky Mountains \citep{Allen_JAMES_2015}. In
Canada, the highest hail probability region is across southern Manitoba and
Saskatchewan and extending northwards into Alberta \citep{Brunet_JAMC_2024}
which agrees well with the ensemble climatology. In Mexico, hailstorms occur
over the high-elevation parts of the south and northwest
\citep{Leon-Cruz_IJC_2023}, aligning with the ensemble's increased hail
probability along the northwest Mexico coast. In summary, while some proxy
ensemble members underestimate the hail probability in the northern Great Plains
of the United States and others overestimate hail probability along the Gulf
Coast, the ensemble reasonably captures the overall spatial distribution of
hail-prone areas in Northern America, Central America, and the Caribbean.

\FloatBarrier

\subsection{South America}

\begin{figure}[h]
\includegraphics[width=\textwidth]{../../results/supplementary/proxy_climatology_south_america}
\caption{As for Figure \ref{fig:proxy_climatology_asia} but for South America.}
\label{fig:proxy_climatology_south_america}
\end{figure}

In South America, the proxy ensemble (Figure
\ref{fig:proxy_climatology_south_america}) shows regions of higher probability
of hail-prone conditions to the east of the Andes, with hotspots in northern
Argentina, Uruguay, southern Paraguay, southern Brazil, southern Bolivia, the
northwest corner of Colombia, and a region covering southeastern Columbia,
southern Venezuela, and northeastern Peru. PH18 shows agreement
for northwestern Argentina with hail probability extending into Uruguay and
Bolivia, but show less hail activity than the proxy ensemble in the north of
the continent. BC19 further confirms the hotspot in the proxy
ensemble over northern Argentina/Uruguay/Paraguay/southern Brazil as well as the
hotspot in northwest Colombia. Regional studies show that northern Argentina and
the border region between Brazil, Argentina and Paraguay is a hail hotspot
\citep{Beal_AR_2020, Nesbitt_BAMS_2021, Bruick_MWR_2019, Martins_AR_2017,
Mezher_AR_2012}. Southern Brazil is well established as a region that
experiences frequent destructive hailstorms \citep{Martins_AR_2017}. A regional
climatology in Argentina shows hotspots in the mid-northwest and northeast,
which are captured by the proxy ensemble, and an isolated hotspot in the south
which the ensemble does not capture \citep{Mezher_AR_2012}. In the north of
South America, hailstorms are known to occur in the Central Andes of Peru
\citep{Valdivia_AMT_2024}. In Colombia, hail is reported across the whole
country, but the most hail-prone regions are in the western, central and eastern
branches of the Andes (the ensemble highlights the eastern side), and in the
Sierra Nevada de Santa Marta in the country's north, which agrees well with the
ensemble \citep{Pena_Beltran_CG_2020}. There is a notable region of
within-ensemble variability across the Peru/Colombia/Brazil border region. The
proxy ensemble captures well the most hail-prone regions in South America.

\FloatBarrier

\subsection{Europe, Northern Africa, Western Asia, and Iran}
\label{sec:europe}

\begin{figure}[h]
\includegraphics[width=\textwidth]{../../results/supplementary/proxy_climatology_europe}
\caption{As for Figure \ref{fig:proxy_climatology_asia} but for Europe, Northern
Africa, and Western Asia.}
\label{fig:proxy_climatology_europe}
\end{figure}

In Europe, Northern Africa, Western Asia, and northern Iran, the proxy ensemble
(Figure \ref{fig:proxy_climatology_europe}) shows hail hotspots in Italy
(especially its north), Croatia, the foothills of the Alps, eastern Spain, and a
swath that runs from southeast to northwest France and into southern Germany.
The high Alps are a local minimum in hail-prone conditions. Hail-prone regions
extend eastwards across Hungary, Romania, and across the Black Sea to Georgia,
Armenia, Azerbaijan, and northern Iran. The ensemble shows the Mediterranean
coasts as particularly hail prone, and the northern edges of the African
continent show hail-prone conditions, particularly in Morocco.
PH18 agrees well, showing similar peaks in northern Italy and
the Pyrenees, the diagonal band across France, the minimum over the high Alps,
the hotspot in eastern Spain, hail-prone conditions in Northern Africa, and the
eastwards extension of hail-prone conditions to northern Iran.
BC19 shows the highest number of hail detections in the
Mediterranean Sea to the southeast of Italy, and generally agrees with the
distribution of hail-prone regions in the ensemble, although the low resolution
of the satellite data somewhat hampers detailed comparison. Regional
climatologies broadly align with the proxy ensemble's distribution of hail-prone
regions. By subregion:

\begin{itemize}
    \item \textbf{Eastern Europe:} The Northern Caucasus has high hail
    occurrence for Eastern Europe \citep{Malkarova_RMH_2011,
    Zharashuev_RMH_2012, Punge_AR_2016}, hail occurs on the Crimean Peninsular
    \citep{Zharashuev_RMH_2012} and in western and southern Russia \citep[][and
    references therein]{Punge_AR_2016}, and large hail has been reported in
    Belarus \citep{Punge_AR_2016}.  In Romania, hail occurs across the country
    \citep{Istrate_GT_2017} with a probable higher concentration in the west
    \citep{Burcea_MWR_2016}; hail frequency increases from the southeast to the
    north and west, and the northwest is a known hotspot \citep{Punge_AR_2016}.
    The Republic of Moldova experiences significant agricultural damage from
    hail \citep{Potapov_RMH_2007}. Hail is common in Bulgaria
    \citep{Simeonov_AR_2009}. In Hungary, Slovakia, and Poland, environmental
    conditions for hail increase in frequency toward the southeast
    \citep{Mohr_GRL_2015}. In Poland there are few hailstorms in the north
    \citep[][and citations therein]{Punge_AR_2016}. The ensemble shows
    relatively uniform hail-prone conditions occurrence for Czechia and
    Slovakia: station data show that Czechia experiences more hail hazard than
    Poland, and more than Slovakia where reports of hail are relatively few
    \citep{Punge_AR_2016}. In Poland, weather stations record hail slightly more
    frequent hail than those in northern Germany, and there is a reported
    minimum in frequency in the southeast \citep{Suwala_QG_2013}, which is not
    shown in the proxy ensemble. Modelling shows more simulated hail in Eastern
    Europe than in Western Europe \citep{Cui_JGRA_2025}. Except for the reported
    minimum in southeast Poland, the ensemble agrees well with published
    climatologies in Eastern Europe.

    \item \textbf{Northern Europe:} Hail is generally uncommon in Northern
    Europe \citep{Punge_AR_2016}. Hail is uncommon in Norway and Denmark
    \citep{Tuovinen_MWR_2009}, but somewhat more frequent in Sweden \citep[][and
    references therein]{Punge_AR_2016}. Finland experiences damaging hail,
    especially in the south and west and rarely in the north
    \citep{Tuovinen_MWR_2009}. In Estonia and Lithuania hail occurs but is not
    common \citep[][and references therein]{Punge_AR_2016}. Hail is uncommon in
    Ireland and the United Kingdom of Great Britain and Northern Ireland, with
    decreasing hail activity from east to west \citep{Mohr_GRL_2015,
    Punge_AR_2016}. These patterns are well captured by the ensemble
    climatology.

    \item \textbf{Southern Europe:} In Portugal, hail is reported mostly in the
    north \citep{Santos_IJC_2019}. In Spain, supercells including hail occur
    particularly in the east along the Mediterranean coast
    \citep{Calvo-Sancho_WCD_2022}, hail is reported most frequently in the east
    and northeast \citep{Saa-Requejo_NHESS_2011}, and conditions are most
    hail-prone along the Mediterranean coast \citep{Mohr_AR_2013}; these regions
    are corroborated by modelling \citep{Cui_JGRA_2025}. Agricultural damages
    from hail are high in the northeast of Spain \citep[][and references
    therein]{Punge_AR_2016}. In Italy, hail occurs across the country but with
    greatest frequency in the north and with regions of lower frequency across
    Central Italy \citep{Baldi_AR_2014, Cui_JGRA_2025}. The pre-alps of Northern
    Italy are among the most hail-prone regions of Europe \citep{Mohr_AR_2013,
    Cui_JGRA_2025, Punge_AR_2016}. In Bosnia and Herzegovina, hailstorms damage
    crops in the north \citep{Dejanovic_2019}. In Serbia, hail occurs most
    frequently in the southwest \citep{Curic_IJC_2016}. Hail is common in
    Slovenia \citep{Punge_AR_2016}, Macedonia \citep{Dimitrievski_JWM_1983}, and
    northern Greece \citep{Sioutas_AR_2009} but less common in southern Greece
    \citep{Punge_AR_2016}. Croatia is hail-prone with high frequency toward the
    coast \citep{Blaskovic_AR_2023, Jelic_JGRA_2020, Mohr_GRL_2015}. Overall,
    the ensemble outputs align with regional climatologies for Southern Europe.

    \item \textbf{Western Europe:} In France, there is a diagonal band of higher
    hail frequency extending from the southwest to northeast, with lower hail
    frequencies in the northwest and southeast
    \citep{Vinet_AR_2001,Fluck_NHESS_2021,Mohr_AR_2013,Cui_JGRA_2025}. The
    southwest near the Pyrenees is particularly hail prone
    \citep{Vinet_AR_2001,Berthet_AR_2011, Berthet_AR_2013} while the Massif
    Central in the centre-east shows high hail activity in radar data
    \citep{Fluck_NHESS_2021} but low activity in an environment-based analysis
    \citep{Mohr_AR_2013}. The ensemble reproduces this overall structure for
    France, although the ensemble's SW-NE band extends slightly further to the
    northwest than those shown in Vinet 2001 \cite{Vinet_AR_2001} and Fluck et
    al., 2021 \cite{Fluck_NHESS_2021}. The frequency of hail-prone conditions
    decreases towards the Atlantic coasts of France, Belgium, and The
    Netherlands \citep{Mohr_GRL_2015, Punge_AR_2016}, and Belgium has lower hail
    frequency than neighbouring regions of France and Germany
    \citep{Lukach_MA_2017, Fluck_NHESS_2021}. In Germany, hail hazard is higher
    in the southern half of the country
    \citep{Mohr_GRL_2015, Fluck_NHESS_2021, Suwala_QG_2013, Cui_JGRA_2025, Punge_AR_2016}
    with hotspots in the Black Forest region \citep{Fluck_NHESS_2021,
    Suwala_QG_2013, Nisi_QJRMS_2016} and a minimum in the northern lowlands
    \citep{Suwala_QG_2013}. In radar data from Switzerland, the pre-alps to the
    north and south of the main Alpine chain, the Black Forest region in
    southwest Germany, and the Jura mountains on the border between Switzerland
    and France, are hail-prone \citep{Nisi_QJRMS_2016}. The high Alps show
    little hail activity \citep{Mohr_GRL_2015, Nisi_QJRMS_2016,
    Kahraman_MWR_2016, Punge_AR_2016}, as reproduced by the ensemble. Hail-prone
    regions in Austria are to the east, out of the main Alpine chain
    \citep{Svabki_ECSS_2013,Punge_AR_2016}. The proxy ensemble aligns closely
    with published regional climatologies for Western Europe.

    \item \textbf{Northern Africa:} There is little detailed climatological
    information for hail in Northern Africa. Hail occurrence is shown across
    Northern Africa in the Mediterranean hail climatology of Laviola et al.,
    2022 \cite{Laviola_RS_2022}, with highest occurrence in Autumn in the region
    around Libya, which aligns with the ensemble climatology.
    
    \item \textbf{Western Asia and Iran:} T\"{u}rkiye is affected by hail, with
    reports concentrated on its Mediterranean coasts in the cold season and
    across the country in summer, with a maximum in hail days in the northeast
    \citep{Kahraman_MWR_2016}. In Armenia, hail is a significant hazard to
    agriculture \citep{Arazyan_EDR_2020}, with higher hail occurrence in the
    north \citep{Harutyunyan_2017}. Georgia is known to be hail prone,
    especially in the east \citep{Varazanashvili_NH_2012} but with hail
    occurring across the territory \citep{Tatishvili_JGGS_2017}. Hail is common
    in Cyprus \citep{Michaelides_NHESS_2008, Nicolaides_AG_2009}. In Iran, hail
    occurs with more prominence in the mountainous regions
    \citep{Salahi_JESS_2018}, and crop losses are recorded in the northwest
    \citep{MirMousavi_JPHGR_2022}. These patterns across Western Asia and Iran
    are well captured by the proxy ensemble.
\end{itemize}

\FloatBarrier

\subsection{Africa}

\begin{figure}[h]
\includegraphics[width=\textwidth]{../../results/supplementary/proxy_climatology_africa}
\caption{As for Figure \ref{fig:proxy_climatology_asia} but for Africa.}
\label{fig:proxy_climatology_africa}
\end{figure}

In Africa, the proxy ensemble (Figure \ref{fig:proxy_climatology_africa}) shows
a band of high hail potential across the sub-Saharan tropics, with hotspots on
the coasts of Nigeria, Benin, and Togo, uniform hail-prone condition occurrence
across Ghana and higher occurrence in the east of C\^ote D'Ivoire, as well as a
hotspot in northwest Democratic Republic of the Congo and the border region with
the Central African Republic and Republic of the Congo. The region extends with
lower hail-prone condition occurrence to the east across South Sudan, southern
Sudan and northern Ethiopia, and to Eritrea. In the south, the obvious hotspot
is in eastern South Africa, where hail-prone conditions spread northwest to the
border with Botswana and north along the east coast into Mozambique. The
southern tip of Madagascar is shown as hail-prone. PH18 and the ensemble broadly
agree on the eastern South Africa and tropical hotspots, though PH18's high
magnitudes are slightly to the north and east of those in the ensemble, and
further inland, and they show hotspots in Angola and in Uganda near Lake
Victoria, both regions in which the ensemble shows reduced hail risk. BC19
broadly agrees with the ensemble, with a large tropical region of high numbers
of hail detections and hotspots in eastern South Africa and Madagascar. Regional
climatologies for southern Africa confirm the eastern South Africa hail hotspot
\citep{Dyson_IJC_2021, Punge_NHESS_2023} with most severe thunderstorm
environments occurring near the coast \citep{Blamey_CD_2017}, although the
reanalysis-based climatology of Dyson et al., 2021 \cite{Dyson_IJC_2021} places
the hail activity maximum slightly further inland. Hail climatology over
tropical Africa remains subject to uncertainty \citep{Bang_JAMC_2019,
Ni_JAMC_2017} with few regional climatologies available, but hail occurs
relatively often in western Kenya \citep{Stephens_AFM_1992, Frisby_JAMC_1967}
and has been reported, mostly rarely, across the rest of the African tropics
\citep{Frisby_JAMC_1967}. Except for missing possible hail activity near Lake
Victoria, the proxy ensemble agrees reasonably well with the limited
climatological information available for Africa.

\FloatBarrier

\section{Case studies of hail-prone day anomalies}
\label{sec:cases}

Monthly multi-proxy mean anomalies in normalised hail-prone days derived using
ERA5 reanalysis showed higher values for months with known occurrences of
damaging hailstorms. The proxies produced higher than climatological average
numbers of hail-prone days for February and March 2015 in northern and central
India (Supplementary Figure \ref{fig:anoms_India_2015}), regions that were
affected by hailstorms that caused major losses to wheat crops in this period
\citep{Chattopadhyay_Mausam_2017, Singh_CS_2017}. Similarly, the proxies
highlighted areas of central and southern Europe as particularly hail-prone in
June 2022 (Supplementary Figure \ref{fig:anoms_Europe_2022}), when the
passage of two low-pressure systems caused high-loss hailstorm outbreaks across
these regions \citep{Pucik_2023}. The proxies also identified April 2015 and
October 2022 as unusually hail-prone months in northeast India and western
France, respectively; there were hailstorms reported in both regions during
these respective months \cite{Chattopadhyay_Mausam_2017, Pucik_2023}. These
case-study results increase our confidence in the ability of the multi-proxy
mean to identify hail-prone conditions worldwide.

\begin{figure*}[h]
    \centering
    \includegraphics[width=\textwidth]{../../results/supplementary/monthly_anoms_India_2015}
    \caption{\textbf{Monthly multi-proxy mean normalised hail-prone day
    anomalies for the Indian region in 2015.} Anomalies are calculated using
    ERA5 data with respect to the monthly ERA5 historical climatology
    (1980-1999), figure shows multi-proxy mean anomalies (n=3 per grid cell).
    The normalisation factor was held constant.}
    \label{fig:anoms_India_2015}
\end{figure*}

\begin{figure*}[h]
    \centering
    \includegraphics[width=\textwidth]{../../results/supplementary/monthly_anoms_France_2022}
    \caption{As for Supplementary Figure \ref{fig:anoms_India_2015} but for
    Europe in 2022.}
    \label{fig:anoms_Europe_2022}
\end{figure*}

\FloatBarrier

\section{Projected changes in proxy ingredients}
\label{sec:projected_ingredients}

Projections of storm-relevant properties showed almost uniform increases in
convective instability extremes as measured by convective available potential
energy (CAPE) and lifted index (LI), and increasing extremes in convective
inhibition (Supplementary Figure \ref{fig:ingredients_changes_1}).
Projections in extremes in 0-6 km bulk wind shear (S06) showed decreases (mixed
increases) in the northern (southern) hemisphere (Supplementary Figure
\ref{fig:ingredients_changes_1}). Temperature-related ingredients increased
as expected in the warmer scenarios (Supplementary Figure
\ref{fig:ingredients_changes_2}). At times when CAPE was extreme, there were
slight reductions in convective inhibition in South America and Africa,
wide-spread increases in melting level height, and mostly non-significant changes
in wind shear (Supplementary Figure
\ref{fig:ingredients_changes_at_extreme_times}).

Crop hail risk projections for these case study regions are provided below. A
region of southern Europe near the Alps showed an overall increase in hail-prone
proportion of cropping season for potatoes, rye, and wheat, with proxy
disagreement across the summer months and agreement on increases from October to
April (Supplementary Figure \ref{fig:crop_lines_eu}). In India for rice, wheat
and maize, there were non-significant increases in cropping season hail-prone
proportion across the southern flank of the Himalaya, but decreases further
south (Supplementary Figure \ref{fig:crop_lines_india}).

\begin{figure*}[h]
    \includegraphics[width=\textwidth]{../../results/supplementary/ingredients_changes_cape}
    \includegraphics[width=0.958\textwidth]{../../results/supplementary/ingredients_changes_shear}
    \includegraphics[width=0.987\textwidth]{../../results/supplementary/ingredients_changes_cin}
    \includegraphics[width=0.976\textwidth]{../../results/supplementary/ingredients_changes_lifted_index}
    \caption{\textbf{Differences in multimodel mean (n=160 per grid point) hail
    ingredients by epoch.} Ingredients shown are annual extreme (99th
    percentile) convective available potential energy (CAPE), annual extreme
    (99th percentile) 0-6 km bulk wind shear (S06), annual extreme (1st
    percentile) convective inhibition (CIN), and annual extreme (1st percentile)
    lifted index. CAPE, CIN, and LI were calculated using a well-mixed parcel
    over the lowest 100 hPa. Stippling shows regions in which at least 50\% of
    the model/proxy combinations agreed with the sign of the mean difference and
    also showed significant differences in the mean ($p < 0.05$ on a two-sided
    Welch's t-test, n=20 years per epoch).}
    \label{fig:ingredients_changes_1}
\end{figure*}

\begin{figure*}[h]
    \includegraphics[width=0.955\textwidth]{../../results/supplementary/ingredients_changes_mlh}
    \includegraphics[width=0.955\textwidth]{../../results/supplementary/ingredients_changes_temp}
    \includegraphics[width=0.955\textwidth]{../../results/supplementary/ingredients_changes_lapse_rate}
    \includegraphics[width=\textwidth]{../../results/supplementary/ingredients_changes_mumr}
    \caption{As for Supplementary Figure \ref{fig:ingredients_changes_1} but for
    annual mean melting level height (MLH), annual mean temperature at 500 hPa
    ($T_{500}$), annual mean lapse rate (LR), and most-unstable parcel mixing
    ratio (MUMR). To increase contrast the colour scale for LR is truncated.}
    \label{fig:ingredients_changes_2}
\end{figure*}

\begin{figure*}[h]
    \includegraphics[width=0.981\textwidth]{../../results/supplementary/ingredients_changes_mlcin_extreme_cape}
    \includegraphics[width=0.963\textwidth]{../../results/supplementary/ingredients_changes_shear_extreme_cape}
    \includegraphics[width=\textwidth]{../../results/supplementary/ingredients_changes_mlh_extreme_cape}
    \caption{As for Supplementary Figure \ref{fig:ingredients_changes_1} but
    showing changes in annual mean CIN, S06, and melting level height (MLH),
    only for times and locations when CAPE is over the 99th percentile
    calculated for each epoch.}
    \label{fig:ingredients_changes_at_extreme_times}
\end{figure*}

\FloatBarrier

\section{Detailed comparison with previous studies}
\label{sec:comparison_prev_studies}

To put our global analysis of changes in hail hazard frequency under climate
change in context, here we show where our projections agree with or contradict
previous results \cite{Raupach_NREE_2021}, by region, while noting that past
results use a wide variety of different data sources, none of which are perfect,
and projection studies are few \cite{Raupach_NREE_2021}. In Asia, our results
match past decreases in hail occurrence found in stations concentrated in
China's east (1980--2012) \cite{Li_JC_2016}, but contradict past decreases in
hail events reported in Mongolia (1993--2013) \cite{Lkhamjav_APJAS_2017}. In
Australia, our significant projections continue observed trends: hail-prone
conditions in reanalysis (1979--2021) have increased in the southeast and
southwest of the country with decreases across the north and centre
\cite{Raupach_npjCAS_2023} (our non-significant projected decreases in frequency
in the southwest contradict these past trends). Projections for small regions in
the southeast have shown no trends in hail losses for doubled CO2 concentrations
\cite{McMaster_CC_1999}. A decrease in frequency in point locations in southwest
Victoria was projected when comparing 1980--2000 to 2040--2060
\cite{Niall_IJC_2005}, although the decreases were based on decreases in
instability that do not agree with more recent analyses \cite{Allen_JC_2014}.

In North America, past trends show a mixed picture \cite{Raupach_NREE_2021}, but
our projections align with some previous results: hailstorm frequency increased
in Alberta, Canada from 1982--1993 compared to 1977--1982 \cite{Etkin_IJC_1999},
there were increases in frequency in the central Rockies with overall USA
decreases (1896--1995), although increases were noted in the high plains and
southeast which contradict our results \cite{Changnon_JC_2000}, and a poleward
shift was found in hail reports since 2000 in the eastern USA
\cite{Liu_ERL_2024}. Regional projections for North America comparing 1971--2000
to 2041--2070 have shown decreases in frequency overall and especially in the
east and southeast \cite{Brimelow_NCC_2017} and a near elimination of surface
hail in Colorado \cite{Mahoney_NCC_2012}, agreeing with our projections. Severe
hail frequency in North America is generally projected to increase
\cite{Trapp_JC_2019}, although summer decreases in severe hail frequency in the
east are projected \cite{Trapp_JC_2019}. In South America, there are few trend
studies and no other projections \cite{Raupach_NREE_2021}; in Argentina our
significant projections contradict observed decreases in the centre and east
over 1960--2008, although there is geographical variability in observed trends
in Argentina \cite{Mezher_AR_2012}.

In Europe, our results showed significant projected increases to the north of
the Alps, agreeing with past increases in Switzerland in insurance data
(1949--1993) \cite{Willemse_1995}, Switzerland (1959--2022)
\cite{Wilhelm_NHESS_2024} in reanalyses, and Southern Germany (1986--2004) in
insurance records \cite{Kunz_IJC_2009}. Much of the rest of southern and central
Europe showed non-significant changes in our analysis, which aligns with the
wide variety of observed trends and corresponding high uncertainty for both
trends and projections in this region \cite{Raupach_NREE_2021}. In Germany,
where our results were non-significant, regional projections to 2050 have shown
increases in hail-related weather types \cite{Kapsch_JGRA_2012} and an increase
in hail potential in the northwest and south \cite{Mohr_JGRA_2015}. Likewise in
central Italy our results were non-significant while a previous regional
projection to 2040 showed an increase in annual hail frequency
\cite{Piani_NHESS_2005}. Increased melting in Atlantic France is projected to
reduce hailstone numbers \cite{Dessens_AR_2015}. Severe hail frequency in Europe
is generally projected to increase by 2100 \cite{Radler_npjCAS_2019} with model
disagreement on instability trends over the United Kingdom
\cite{Sanderson_IJC_2015}.

\FloatBarrier

\newpage
\section{Supplementary tables and figures}
\label{sec:supp_figures}

<<runsTable, echo=FALSE, results="asis">>=
runs = read_csv('../../results/runs_list.csv', col_types='cccccciiccccc')
runs = runs %>% arrange(model) %>% select(Model=model, 
                                          Institution=institution_id,
                                          Experiment=exp,
                                          Ensemble=ensemble, 
                                          Start=start_year, 
                                          End=end_year,
                                          Res=nominal_resolution,
                                          Vert=vertical_levels,
                                          Orog=backup_orography) %>%
                                          mutate(Orog=case_when(Orog=='False'~'', Orog=='True'~'X'))
tab = xtable(runs, label='tab:model_details',
             caption='\\textbf{CMIP6 model details}. ``Res\'\' is nominal model resolution, ``Vert\'\' is the number of vertical levels in the model. An X in the column ``Orog\'\' indicates models for which no orography was provided; in these cases the orography for the historical run of CNRM-CM6-1 was interpolated to the model grid for use here. We used data at 6-hourly temporal resolution.')
print(tab, booktabs=TRUE, include.rownames=FALSE, 
      size='footnotesize', table.placement='h')
@

\begin{table}[h]
    \centering
    \begin{tabular}{llll}
        \toprule
        Model & Experiment & Citation & License \\ 
        \midrule
        CMCC-CM2-SR5 & historical & \cite{CMCC-CM2-SR5_historical} & CC BY 4.0 \\
        CMCC-CM2-SR5 & ssp585 & \cite{CMCC-CM2-SR5_ssp585} & CC BY 4.0 \\
        CMCC-ESM2 & historical & \cite{CMCC-ESM2_historical} & CC BY 4.0 \\
        CMCC-ESM2 & ssp585 & \cite{CMCC-ESM2_ssp585} & CC BY 4.0 \\
        CNRM-CM6-1 & historical & \cite{CNRM-CM6-1_historical} & CC BY 4.0 \\
        CNRM-CM6-1 & ssp585 & \cite{CNRM-CM6-1_ssp585} & CC BY 4.0 \\
        EC-Earth3 & historical & \cite{EC-Earth3_historical} & CC BY 4.0 \\
        EC-Earth3 & ssp585 & \cite{EC-Earth3_ssp585} & CC BY 4.0 \\
        GISS-E2-1-G & historical & \cite{NASA-GISS_historical} & CC0 1.0 \\
        GISS-E2-1-G & ssp585 & \cite{NASA-GISS_ssp585} & CC0 1.0 \\
        MIROC6 & historical & \cite{MIROC_historical} & CC BY 4.0 \\
        MIROC6 & ssp585 & \cite{MIROC_ssp585} & CC BY 4.0 \\
        MPI-ESM1-2-HR & historical & \cite{MPI-ESM1-2-HR_historical} & CC BY 4.0 \\
        MPI-ESM1-2-HR & ssp585 & \cite{MPI-ESM1-2-HR_ssp585} & CC BY 4.0 \\
        MRI-ESM2-0 MRI & historical & \cite{MRI-ESM2-0_historical} & CC BY 4.0 \\
        MRI-ESM2-0 MRI & ssp585 & \cite{MRI-ESM2-0_ssp585} & CC BY 4.0 \\
        \bottomrule
    \end{tabular}
    \caption{\textbf{References and licenses for CMIP6 data}.}
    \label{tab:CMIP6_data_refs}
\end{table}

\begin{figure*}[h]
    \centering
    \includegraphics[width=0.81\textwidth]{../../results/supplementary/all_drivers}
    \caption{\textbf{Drivers of changes across models.} As for main text Figure
    \ref{main-fig:drivers} but showing all ingredients. Rows show de-biased
    ingredients: freezing level height (FLH), lapse rate (LR), melting level
    height (MLH), mixed-layer CAPE (MLCAPE$_{100}$), mixed-layer CIN
    (MLCIN$_{100}$), lifted index (LI), most-unstable CAPE (MUCAPE$_{250}$),
    most-unstable mixing ratio (MUMR), 0-6 km bulk shear (S06), and temperature
    at 500 hPa (T500).}
    \label{fig:drivers}
\end{figure*}

\begin{figure*}[h]
    \centering
    \includegraphics[width=\textwidth]{../../results/supplementary/changes_crop_proportion_hail_prone_3C}
    \caption{\textbf{Change in multimodel, multi-proxy mean hail-prone
    proportions of cropping seasons for 3 \degr{} warming.} n=480 per grid cell.
    Stippling as for Supplementary Figure \ref{fig:ingredients_changes_1} and
    region subset as for Extended Data Figure
    \ref{ED-fig:historic_crop_proportions}.}
    \label{fig:crop_changes_3C}
\end{figure*}

\begin{figure*}[h]
    \centering
    \includegraphics[width=\textwidth]{../../results/supplementary/crop_lines_af}
    \caption{\textbf{Changes affecting crops at a selected location in Africa.}
    The horizontal black lines in the top inset plot indicate which months are
    considered cropping times for selected crops at the given location. The
    chosen location is at the centre of the fuchsia square in the inset maps.
    Inset maps show changes in hail-prone proportion of cropping season by crop.
    Lines in main plot show mean changes in hail-prone days per month over a
    4$\times$4\degr{} region around the chosen location (shown as a fuchsia
    square in inset maps), with vertical lines indicating the inter-model range
    per proxy (n=2560 per month). Changes and stippling in inset maps as for
    Extended Data Figure \ref{ED-fig:crop_changes_africa}.}
    \label{fig:crop_lines_af}
\end{figure*}

\begin{figure*}[h]
    \centering
    \includegraphics[width=\textwidth]{../../results/supplementary/crop_lines_as}
    \caption{As for Figure \ref{fig:crop_lines_af} but for Asia.}
    \label{fig:crop_lines_as}
\end{figure*}

\begin{figure*}[h]
    \centering
    \includegraphics[width=\textwidth]{../../results/supplementary/crop_lines_au}
    \caption{As for Figure \ref{fig:crop_lines_af} but for Australia.}
    \label{fig:crop_lines_au}
\end{figure*}

\begin{figure*}[h]
    \centering
    \includegraphics[width=\textwidth]{../../results/supplementary/crop_lines_us}
    \caption{As for Figure \ref{fig:crop_lines_af} but for the USA.}
    \label{fig:crop_lines_ca}
\end{figure*}

\begin{figure*}[h]
    \centering
    \includegraphics[width=\textwidth]{../../results/supplementary/crop_lines_eu}
    \caption{As for Figure \ref{fig:crop_lines_af} but for Europe.}
    \label{fig:crop_lines_eu}c
\end{figure*}

\begin{figure*}[h]
    \centering
    \includegraphics[width=\textwidth]{../../results/supplementary/crop_lines_nz}
    \caption{As for Figure \ref{fig:crop_lines_af} but for New Zealand.}
    \label{fig:crop_lines_nz}
\end{figure*}

\begin{figure*}[h]
    \centering
    \includegraphics[width=\textwidth]{../../results/supplementary/crop_lines_india}
    \caption{As for Figure \ref{fig:crop_lines_af} but for India.}
    \label{fig:crop_lines_india}
\end{figure*}

\begin{figure*}[h]
    \centering
    \includegraphics[width=\textwidth]{../../results/supplementary/run_years}
    \caption{\textbf{CMIP6 models and per-degree-framework date ranges.} The
    reference period from historical simulations is shown in blue, while periods
    with 2 and 3 \degr{} warming over the reference period, in SSP5-8.5
    simulations, are in orange and green respectively.}
    \label{fig:epochs}
\end{figure*}

\FloatBarrier
\begin{table}
    \footnotesize
    \centering
<<crop_n_table_spatial, echo=FALSE, results="asis">>=
    lines <- readLines("../../results/crop_n_spatial_table.tex")
    lines <- gsub(' / ', '/', lines)
    cat(lines, sep = '\n')
@
\caption{Global spatial average of per-pixel mean hail-prone proportion
of cropping period (Mean HPP) by crop in the historical epoch, and the
number of samples in the spatial mean.}
\label{tab:crop_spatial_samples}
\end{table}

\FloatBarrier
\newpage

\section{Proxy formulas}
\label{sec:proxy-formulas}

Three proxies were used in this work: Raupach, Eccel, and SHIP.

\subsection{Raupach proxy}
\label{sec:raupach_proxy}

The Raupach proxy is the modified proxy of Raupach et al., 2023
\cite{Raupach_MWR_2023}. This proxy was trained in Australia, a continent that
covers most types of hail environments, and the proxy was specifically designed
to adapt to latitudinal changes in hail environments \citep{Raupach_MWR_2023}.
Comparisons of proxy output with radar data showed reasonable co-fluctuation
\citep{Raupach_npjCAS_2023}. Here we slightly modified the original proxy to
make it more suitable for application in cold environments. The Raupach proxy
indicates hail-prone conditions when

\begin{eqnarray}
    \textrm{MLCAPE}_{100} \times {S_{06}}^\alpha & \geq & \beta, \label{eq:discrim} \\
    \textrm{LR} & < & -5.45 \textrm{ K km}^{-1} \label{eq:extra_conditions_1}, \\
    \textrm{LI}_{100} & < & 0.4 \textrm{ K} \label{eq:extra_conditions_2}, \\
    T_{500} & < & 265.46 \textrm{ K} \label{eq:extra_conditions_3},
\end{eqnarray}

\noindent where MLCAPE$_{100}$ (J kg$^{-1}$) is convective available potential
energy calculated using a well-mixed parcel over the lowest 100 hPa of the
atmosphere, $S_{06}$ (m s$^{-1}$) is 0-6 km bulk vertical wind shear, LR (K
km$^{-1}$) is the lapse rate between 700 hPa and 500 hPa, LI$_{100}$ (K) is the
lifted index \citep{Galway_BAMS_1956} defined using same parcel as that used by
MLCAPE$_{100}$, $T_{500}$ (K) is the temperature at 500 hPa, and $\alpha$ and
$\beta$ are parameters that vary with the melting level height such that

\begin{equation}
\alpha = 
    \begin{cases} 
        0.00127 \times \textrm{MLH} - 1.88272 & \textrm{ if }\quad\textrm{MLH} \geq 2000 \textrm{ m} \\
        0.00127 \times 2000 - 1.88272 & \textrm{ if }\quad\textrm{MLH} < 2000 \textrm{ m}\\
    \end{cases},
    \label{eq:newalpha}
\end{equation}

and 

\begin{equation}
\log_{10}(\beta) =
    \begin{cases}
    0.00204 \times \textrm{MLH} - 1.75631 & \textrm{ if }\quad\textrm{MLH} \geq 2000 \textrm{ m} \\
    0.00204 \times 2000 - 1.75631 & \textrm{ if }\quad\textrm{MLH} < 2000 \textrm{ m} \\
    \end{cases}.
    \label{eq:newbeta}
\end{equation}

\noindent where MLH (m) is melting level height, where wet-bulb temperature is
zero C, above sea level. The idea behind the parameters $\alpha$ and $\beta$ is
that there is a latitudinal dependence on the proportion of instability versus
shear in environments in which hailstorms occur in Australia
\citep{Raupach_MWR_2023}. Storms in the south, where shear is generally high and
melting level height is low, are more easily discriminated by MLCAPE$_{100}$
values, while storms in the tropics, where MLCAPE$_{100}$ and melting level
height are both generally high, are more easily discriminated by shear
\citep{Raupach_MWR_2023}. The proxy uses MLH to adjust the values of $\alpha$
and $\beta$ and therefore to adjust the discriminator between hail and no-hail
conditions in instability-shear space. 

\subsubsection{Modifications made to proxy}

In the original proxy of Raupach et al., 2023 \cite{Raupach_MWR_2023}, $\alpha$
and $\beta$ were set as follows:

\begin{eqnarray}
\alpha & = & 0.00127 \times \textrm{MLH} - 1.88272, \label{eq:alpha} \\
\log_{10}(\beta) & = & 0.00204 \times \textrm{MLH} - 1.75631. \label{eq:beta}
\end{eqnarray}

\noindent Figure \ref{fig:proxy_by_MLH} shows the original proxy
\citep{Raupach_MWR_2023} discriminator lines (set by Equations \ref{eq:discrim},
\ref{eq:alpha}, and \ref{eq:beta}) for various values of melting level height
(MLH). When the MLH is below about 1500 m, the value of $\alpha$ becomes
negative and the value of $\beta$ becomes very small, and the proxy stops
detecting high-CAPE, high-shear conditions. So that the proxy is more reliable
in colder regions where the melting level height is below 1500 m, in this work
we have modified the proxy such that when the MLH is below 2000 m, the values of
$\alpha$ and $\beta$ for an MLH of 2000 m are used (Equations \ref{eq:newalpha}
and \ref{eq:newbeta}). This modification means the proxy is always able to
detect high-CAPE, high-shear conditions.

\begin{figure*}[!ht]
    \centering
    \includegraphics[width=\textwidth]{../../results/supplementary/proxy_by_MLH}
    \caption{\textbf{Original proxy for various values of melting level height
    (MLH).} CAPE stands for convective available potential energy. $S_{06}$ is
    0-6 km bulk vertical wind shear. The same discriminator lines are shown on
    logarithmic and linear scales.}
    \label{fig:proxy_by_MLH}
\end{figure*}

\subsubsection{Raupach proxy extra conditions}

Raupach et al., 2023 \cite{Raupach_MWR_2023} defined three ``extra conditions''
or thresholds (shown here as Equations \ref{eq:extra_conditions_1},
\ref{eq:extra_conditions_2}, and \ref{eq:extra_conditions_3}) designed to remove
false positives from hail-prone conditions produced by Equation
\ref{eq:discrim}. With and without the slight modification for MLH, our tests
showed these conditions are similarly effective in removing false positives from
the whole proxy training data set.  
It is notable that the projected changes in the updated Raupach proxy that we
report in this work are not driven primarily by the ``extra conditions'', as
shown by Supplementary Figure \ref{fig:Raupach_extra_conds}.

\begin{figure*}[h!]
    \centering
    \includegraphics[width=\textwidth]{../../results/supplementary/Raupach_extra_conds_3C}
    \caption{\textbf{Effect of extra conditions on Raupach proxy for 3 \degr{}
    warming}. Changes shown are in multimodel mean annual hail-prone days (n=160
    per grid point). On left, the updated Raupach proxy with extra conditions
    applied; on right, changes in the updated Raupach proxy without extra
    conditions applied.}
    \label{fig:Raupach_extra_conds}
\end{figure*}

\subsubsection{Validation of modification}

To assess the impact of the changed calculation of $\alpha$ and $\beta$ we
tested on two datasets:

\begin{enumerate}
    \item On the original training dataset from Raupach et al., 2023
    \cite{Raupach_MWR_2023}: proxy performance metrics for the proxy with no
    extra conditions are similar between versions while the performance of the
    proxy with extra conditions is not affected by the change.
    \item On the climatology data used in Raupach et al., 2023
    \cite{Raupach_npjCAS_2023} covering storm-prone hours of the day from
    1979-2022 across all of Australia: the proxy changes affect the ocean areas
    in the south and southeast of the domain, with changes in mean annual
    hail-prone days of up to $\sim$2. However, over the whole map no location
    had more than
    \Sexpr{ceiling(as.numeric(results_proxy_update['max_percent_diff_per_pixel_all'])*100)/100}\%
    of its values affected and over land no location had more than
    \Sexpr{ceiling(as.numeric(results_proxy_update['max_percent_diff_per_pixel_land'])*100)/100}\%
    of its values affected. The climatology and trends calculated using either
    version of the proxy are very similar for Australia.
\end{enumerate}

\subsection{Eccel proxy}

The Eccel proxy, of Eccel et al., 2012 \cite{Eccel_IJC_2012}, defines an
environment as hail prone when 

\begin{eqnarray}
\textrm{MLCAPE}_{100} \times S_{06} > 10000,&\textrm{and} \\
\textrm{MLCIN}_{100} > -50,
\end{eqnarray}

\noindent where MLCIN$_{100}$ (J kg$^{-1}$) is convective inhibition for a
well-mixed parcel over the lowest 100 hPa of the atmosphere. 

\subsection{SHIP}

The SHIP proxy refers to the significant hail parameter
\citep[SHIP,][]{SPC_SHIP} which is defined by calculating an initial value,
SHIP$_i$, as

\begin{equation}
\textrm{SHIP}_i = \frac{\textrm{MUCAPE}_{250} \times \textrm{MR} \times \textrm{LR} \times -T_{500} \times S_{06}}{42000000},
\label{eq:SHIP}
\end{equation}

\noindent where MUCAPE$_{250}$ (J kg$^{-1}$) is the convective available
potential energy for the ``most unstable'' parcel, defined as the parcel with
the largest equivalent potential temperature over the lowest 250 hPa of the
atmosphere, MR (g kg$^{-1}$) is the mixing ratio for that parcel, and $T_{500}$
is the temperature at 500 hPa in \degr{}. SHIP$_i$ is only defined when 

\begin{eqnarray}
7 \leq \textrm{S06} \leq 27 \textrm{ m s}^{-1}, & \textrm{and} \\
11 \leq \textrm{MR} \leq 13.6 \textrm{ g kg}^{-1}, &
\end{eqnarray}

\noindent and if $T_{500} > -5.5$ degrees C, then a value of $T_{500} = -5.5$ is
used. Once SHIP$_i$ has been calculated using Equation \ref{eq:SHIP} and these
constraints, the following modifications are made to get the final value of
SHIP:

\begin{eqnarray}
\textrm{SHIP} = \textrm{SHIP}_i \times \frac{\textrm{MUCAPE}_{250}}{1300}, & \textrm{if MUCAPE}_{250} < 1300 \textrm{ J kg}^{-1} \\ 
\textrm{SHIP} = \textrm{SHIP}_i \times \frac{\textrm{LR}}{5.8}, & \textrm{if LR} < 5.8 \textrm{ K km}^{-1} \\
\textrm{SHIP} = \textrm{SHIP}_i \times \frac{\textrm{FLH}}{2400}, & \textrm{if FLH} < 2400 \textrm{ m AGL},
\end{eqnarray}

\noindent where FLH is freezing-level height (height of dry-bulb zero degrees C)
and AGL stands for above ground level (note Raupach et al., 2023
\cite{Raupach_MWR_2023} used FLH above sea level for Australia, but here we use
FLH AGL as per both the original SHIP definition and PH18). We considered an
environment to be hail prone when SHIP $> 0.1$, following Raupach et al., 2023
\cite{Raupach_MWR_2023}.

\FloatBarrier
\footnotesize

\bibliography{../main/library}

\end{document}